# -*- coding: utf-8 -*-
import csv

GENERALS = ["income_employment","income_benefits_state_support","income_other","housing",
"utilities_household_bills","council_tax_government","groceries_household_essentials",
"eating_drinking_out","clothing_personal_care","home_garden","general_retail_marketplaces",
"transport_motoring","travel_holidays","entertainment_leisure","digital_subscriptions_services",
"health_medical","insurance","credit_loan_repayments","high_cost_distress_credit","gambling",
"fees_charges","savings_investments","transfers","cash","childcare_education","pets",
"charitable_political_giving","business_self_employment","unclassified"]

# defaults per general: (necessity, cash_flow_type)
D = {
"income_employment":("not_applicable","income"),"income_benefits_state_support":("not_applicable","income"),
"income_other":("not_applicable","income"),"housing":("essential","spend"),
"utilities_household_bills":("essential","spend"),"council_tax_government":("essential","spend"),
"groceries_household_essentials":("essential","spend"),"eating_drinking_out":("discretionary","spend"),
"clothing_personal_care":("mixed_basket","spend"),"home_garden":("mixed_basket","spend"),
"general_retail_marketplaces":("mixed_basket","spend"),"transport_motoring":("essential","spend"),
"travel_holidays":("discretionary","spend"),"entertainment_leisure":("discretionary","spend"),
"digital_subscriptions_services":("discretionary","spend"),"health_medical":("essential","spend"),
"insurance":("essential","spend"),"credit_loan_repayments":("essential","debt_repayment"),
"high_cost_distress_credit":("essential","debt_repayment"),"gambling":("discretionary","spend"),
"fees_charges":("not_applicable","fee_or_penalty"),"savings_investments":("not_applicable","transfer_own_accounts"),
"transfers":("not_applicable","transfer_own_accounts"),"cash":("not_applicable","transfer_own_accounts"),
"childcare_education":("essential","spend"),"pets":("discretionary","spend"),
"charitable_political_giving":("discretionary","spend"),"business_self_employment":("mixed_basket","spend"),
"unclassified":("mixed_basket","spend")}

# (detailed, general, [equifax sub sources], [plaid detailed sources], overrides dict)
L=[
# ---- INCOME
("salary","income_employment",["primary:Identified Salary"],["INCOME_SALARY"],{"o":"recurring_income"}),
("salary_gig","income_employment",["primary:Identified Salary + sub:Taxis|Delivery|Take Away"],[],{}),
("income_agency_work","income_employment",["Recruitment Services","Employment Agencies"],[],{}),
("employee_benefits","income_employment",["Employee Rewards"],[],{}),
("benefits_state","income_benefits_state_support",["primary:Benefits","primary:Welfare"],["INCOME_GOVERNMENT_INCOME"],{"o":"recurring_income"}),
("housing_benefit","income_benefits_state_support",["Housing Benefits"],[],{}),
("pension_received","income_other",["primary:Pension Payout"],[],{"o":"recurring_income"}),
("savings_interest_received","income_other",["Bank Interest Accrual","primary:Interest","primary:Interests and Dividends"],["INTERESTS_AND_DIVIDENDS_INTERESTS_AND_DIVIDENDS","INTEREST_PAYMENTS_INTEREST_RECEIVED"],{}),
("dividend_received","income_other",["Dividend"],[],{}),
("tax_refund","income_other",["primary:Tax Refund"],["TAX_REFUND_TAX_REFUND"],{}),
("refund_received","income_other",["primary:Refund"],[],{}),
("cashback","income_other",["primary:Cash Back","Cashback rewards"],[],{}),
("income_other_unspecified","income_other",[],["INCOME_OTHER"],{}),
# ---- HOUSING
("rent","housing",["Property Rental"],["RENT_AND_UTILITIES_RENT"],{"p":"true","w":"LOW IV 0.0093 - detection gap, do not trust features yet"}),
("mortgage","housing",["Mortgages"],["LOAN_PAYMENTS_MORTGAGE_AND_AUTO"],{"d":"true","p":"true","c":"debt_repayment"}),
("property_management","housing",["Property Management"],[],{"p":"true"}),
("estate_agent","housing",["Estate Agents"],[],{"n":"mixed_basket"}),
("storage","housing",["Storage"],[],{"n":"discretionary"}),
("housing_other","housing",["primary:Rent and Mortgage"],[],{}),
# ---- UTILITIES
("energy","utilities_household_bills",["Energy Providers"],["RENT_AND_UTILITIES_GAS_AND_ELECTRICITY"],{"p":"true"}),
("heating_oil","utilities_household_bills",["Heating Oil"],[],{"p":"true"}),
("water","utilities_household_bills",["Water Companies"],["RENT_AND_UTILITIES_WATER"],{"p":"true"}),
("tv_licence","utilities_household_bills",["TV Licences"],[],{"p":"true"}),
("mobile_phone_contract","utilities_household_bills",["Mobile Phone Contracts"],["RENT_AND_UTILITIES_TELECOMMUNICATIONS"],{"w":"STRONGEST RAYLO ANALOGUE - IV 0.1193 on persistence"}),
("broadband_tv_phone","utilities_household_bills",["Internet, TV and Phone"],["RENT_AND_UTILITIES_INTERNET_AND_CABLE"],{}),
("waste_services","utilities_household_bills",["Waste Services","Recycling"],[],{}),
("utility_other","utilities_household_bills",["primary:Utilities"],["RENT_AND_UTILITIES_OTHER_UTILITIES"],{"p":"true"}),
# ---- COUNCIL TAX & GOVERNMENT
("council_tax","council_tax_government",["Council"],["GOVERNMENTS_AND_NON_PROFIT_GOVERNMENTS_AND_NON_PROFIT"],{"p":"true","w":"debit only; credit direction = council employee salary"}),
("tax_payment","council_tax_government",["primary:Tax"],["INSURANCE_AND_TAX_TAX_PAYMENT"],{"p":"true"}),
("government_services","council_tax_government",["Government Services","primary:Government"],["GOVERNMENTS_AND_NON_PROFIT_OTHER_GOVERNMENTS_AND_NON_PROFIT"],{}),
("id_documents","council_tax_government",["ID Cards"],[],{}),
("emergency_services","council_tax_government",["Emergency Services"],[],{}),
# ---- GROCERIES
("groceries","groceries_household_essentials",["General Groceries"],["FOOD_RETAIL_GROCERIES","FOOD_RETAIL_OTHER","GENERAL_MERCHANDISE_SUPERSTORES"],{"w":"general food shops: supermarkets, food discounters (Aldi/Lidl/Farmfoods/Heron) and symbol-group grocers (Spar/Nisa/Costcutter/Londis/Premier)"}),
("discount_store","groceries_household_essentials",["Discount Stores"],["GENERAL_MERCHANDISE_DISCOUNT_STORES"],{"w":"general-merchandise discount variety (B&M, Home Bargains, Poundland); food discounters are groceries"}),
("convenience_store","groceries_household_essentials",["Newsagents and Convenience Stores"],["GENERAL_MERCHANDISE_CONVENIENCE_STORES"],{"n":"mixed_basket","w":"newsagent/corner-shop style (McColl's, motorway services); chains that are primarily food shops are groceries"}),
("cash_and_carry","groceries_household_essentials",["Cash & Carry"],[],{"w":"membership/trade wholesale (Booker, Costco)"}),
("groceries_specialist","groceries_household_essentials",["Fairtrade and ethical products"],[],{"w":"single-category or specialist food retailers: butchers, world-food grocers, organic, doorstep milk"}),
("confectionary","groceries_household_essentials",["Confectionary"],[],{"n":"discretionary"}),
("alcohol_beer_spirits","groceries_household_essentials",["Alcoholic Beverages Beers and Spirits"],["FOOD_RETAIL_LIQUOR_STORES"],{"n":"discretionary","a":"true","w":"OVERRIDE - Equifax files as Household Essentials"}),
("alcohol_wine","groceries_household_essentials",["Alcoholic Beverages Wines"],[],{"n":"discretionary","a":"true","w":"OVERRIDE - Equifax files as Household Essentials"}),
("tobacco","groceries_household_essentials",["Tobacco Products"],[],{"n":"discretionary","a":"true"}),
("vaping","groceries_household_essentials",["Electronic Cigarettes"],[],{"n":"discretionary","a":"true","w":"OVERRIDE - Equifax files under Personal Healthcare"}),
# ---- EATING OUT
("takeaway","eating_drinking_out",["Take Away","Chip Shed Bourton Limited","Ipswich 5 Star Ltd"],[],{"w":"fast food, chip shops and delivery apps (McDonald's, KFC, Just Eat, Deliveroo, Uber Eats)"}),
("restaurant_cafe","eating_drinking_out",["Restaurants, Cafes and Bistros"],["DINING_DINING","DINING_OTHER_DINING","DINING_COFFEE"],{"w":"eat-in/table service plus cafes, coffee shops and fast-casual (Nando's, Pret, Greggs, Leon)"}),
("pub_bar","eating_drinking_out",["Pubs and Bars"],["DINING_WINE_BARS_AND_PUBS"],{"a":"true"}),
("night_club","eating_drinking_out",["Night Clubs"],[],{"a":"true"}),
("catering","eating_drinking_out",["Catering"],[],{}),
("eating_out_other","eating_drinking_out",["primary:Restaurants and takeaway"],[],{}),
# ---- CLOTHING & PERSONAL CARE
("clothing_general","clothing_personal_care",["General Fashion"],["GENERAL_MERCHANDISE_APPAREL_AND_ACCESSORIES"],{}),
("clothing_womens","clothing_personal_care",["Womens Fashion"],[],{}),
("clothing_mens","clothing_personal_care",["Mens Fashion"],[],{}),
("clothing_childrens","clothing_personal_care",["Childrens Fashion"],[],{}),
("clothing_maternity","clothing_personal_care",["Maternity Clothing"],[],{"w":"life-event signal"}),
("clothing_outdoor","clothing_personal_care",["Outdoor Clothing"],[],{"n":"discretionary"}),
("clothing_workwear","clothing_personal_care",["Workwear"],[],{"n":"essential"}),
("footwear","clothing_personal_care",["Footwear"],[],{}),
("sportswear","clothing_personal_care",["Sportswear"],["GENERAL_MERCHANDISE_SPORTING_GOODS"],{"n":"discretionary"}),
("jewellery","clothing_personal_care",["Jewellery and Accesories"],[],{"n":"discretionary"}),
("fancy_dress","clothing_personal_care",["Fancy Dress"],[],{"n":"discretionary"}),
("health_beauty_general","clothing_personal_care",["General Health and Beauty"],["PERSONAL_CARE_OTHER_PERSONAL_CARE"],{"n":"discretionary"}),
("skin_hair_care","clothing_personal_care",["Skin and Hair Care"],["PERSONAL_CARE_HAIR_AND_BEAUTY"],{"n":"discretionary"}),
("beauty_treatment","clothing_personal_care",["Beauty & Massage"],[],{"n":"discretionary"}),
("fragrances","clothing_personal_care",["Fragrances"],[],{"n":"discretionary"}),
# ---- HOME & GARDEN
("home_accessories","home_garden",["Home Accessories"],["GENERAL_MERCHANDISE_FURNITURE_AND_HARDWARE"],{}),
("home_improvement","home_garden",["Home Improvements"],["GENERAL_SERVICES_HOME_IMPROVEMENT_SERVICES"],{}),
("tools","home_garden",["Tools"],[],{}),
("garden","home_garden",["Garden Accessories","Plants"],[],{"n":"discretionary"}),
("kitchen","home_garden",["Kitchens and Kitchen Accessories"],[],{}),
("bathroom","home_garden",["Bathroom Furniture and Accessories"],[],{}),
("bedding","home_garden",["Bedding"],[],{}),
("lighting","home_garden",["Lights and Lamps"],[],{}),
("household_appliances","home_garden",["Household Appliances"],[],{}),
("home_repair","home_garden",["Household Repair Services"],[],{"n":"essential"}),
("tradesmen","home_garden",["Tradesmen"],[],{"n":"essential"}),
("construction_services","home_garden",["Construction"],[],{}),
("cleaning_services","home_garden",["Cleaning Services"],[],{"n":"discretionary"}),
("laundry","home_garden",["Laundry Services"],[],{"n":"essential"}),
# ---- GENERAL RETAIL
("marketplace_amazon","general_retail_marketplaces",["Amazon","primary:Amazon All"],[],{"w":"Amazon ONLY (incl. Amazon Marketplace); all other marketplaces are marketplace_general. IV 0.1629 persistence; decays sharply at month12"}),
("marketplace_general","general_retail_marketplaces",[],["GENERAL_MERCHANDISE_ONLINE_MARKETPLACES"],{"w":"non-Amazon online marketplaces (eBay, Vinted, Depop, Etsy); split from marketplace_amazon 2026-08-19 to keep the Amazon-specific signal clean"}),
("marketplace_refurbished","general_retail_marketplaces",["Back Market Uk Ltd"],[],{"w":"refurbished-device marketplace - Raylo-adjacent"}),
("payment_intermediary","general_retail_marketplaces",["E-Commerce Payment System"],[],{"w":"PayPal/Klarna-style - obscures underlying merchant"}),
("retail_tv_online_shopping","general_retail_marketplaces",["TV and Online Shopping"],[],{}),
("catalogue_retail","general_retail_marketplaces",["General Catalogues"],[],{"w":"often implies embedded credit"}),
("department_store","general_retail_marketplaces",["Department Stores"],["GENERAL_MERCHANDISE_DEPARTMENT_STORES"],{}),
("retail_small_independent","general_retail_marketplaces",["Small Retail"],[],{}),
("computing_devices","general_retail_marketplaces",["Computers, Laptops and Tablets"],["GENERAL_MERCHANDISE_COMPUTERS_AND_ELECTRONICS"],{"w":"device-adjacent - Raylo relevant"}),
("mobile_handset","general_retail_marketplaces",["Mobile Handsets and Accessories"],[],{"w":"DIRECTLY Raylo-competitive purchase"}),
("computer_peripherals","general_retail_marketplaces",["Computer Peripherals and Accessories"],[],{}),
("printing_supplies","general_retail_marketplaces",["Printers, Printer Ink and Printer Toner"],[],{}),
("electrical_goods","general_retail_marketplaces",["General Electrical"],[],{}),
("audio_equipment","general_retail_marketplaces",["Audio Equipment"],[],{"n":"discretionary"}),
("gadgets","general_retail_marketplaces",["Gadgets and Gizmos"],[],{"n":"discretionary"}),
("camera_photography","general_retail_marketplaces",["Cameras and Photography"],[],{"n":"discretionary"}),
("toys","general_retail_marketplaces",["Toy Stores"],[],{"n":"discretionary"}),
("baby_products","general_retail_marketplaces",["General Baby Products","Baby Gifts"],[],{"w":"life-event signal"}),
("gifts_flowers","general_retail_marketplaces",["Gifts Flowers and Parties"],[],{"n":"discretionary","w":"OVERRIDE - Equifax files as Household Essentials"}),
("stationery","general_retail_marketplaces",["Stationery"],[],{}),
("vouchers","general_retail_marketplaces",["Vouchers/Discount Codes"],[],{}),
("delivery_courier","general_retail_marketplaces",["Delivery"],[],{}),
("retail_other","general_retail_marketplaces",["primary:Shopping (Discretionary)","primary:Shopping (Home)","primary:Shopping (Fashion)","primary:Shopping (Household Essentials)"],["GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE"],{}),
# ---- TRANSPORT
("fuel","transport_motoring",["Fuel"],[],{"w":"Plaid bundles fuel with maintenance"}),
("public_transport_rail_coach","transport_motoring",["Trains and Coaches"],["TRAVEL_AND_TRANSPORTATION_PUBLIC_TRANSIT"],{}),
("taxi_rideshare","transport_motoring",["Taxis"],["TRAVEL_AND_TRANSPORTATION_TAXIS_AND_RIDE_SHARES"],{"n":"mixed_basket"}),
("car_parking","transport_motoring",["Car Parking"],[],{}),
("road_tax","transport_motoring",["Road Tax"],[],{}),
("tolls","transport_motoring",["Tolls and Crossings"],[],{}),
("vehicle_maintenance","transport_motoring",["Garages and Parts"],["TRAVEL_AND_TRANSPORTATION_AUTOMOTIVE"],{}),
("vehicle_mot","transport_motoring",["M.O.T."],[],{}),
("vehicle_servicing","transport_motoring",["Car Services"],[],{}),
("spares_repairs","transport_motoring",["Spares and Repairs"],[],{}),
("carwash","transport_motoring",["Carwash"],[],{"n":"discretionary"}),
("breakdown_cover","transport_motoring",["Breakdown Cover"],[],{}),
("vehicle_purchase","transport_motoring",["Car Dealerships"],[],{"n":"mixed_basket"}),
("car_hire","transport_motoring",["General Car Hire"],[],{"n":"discretionary"}),
("bicycle","transport_motoring",["Bikes and Accessories"],[],{"n":"mixed_basket"}),
("transport_other","transport_motoring",["primary:Commuting and travel","primary:Automotive"],["TRAVEL_AND_TRANSPORTATION_OTHER_TRAVEL_AND_TRANSPORTATION"],{}),
# ---- TRAVEL
("flights","travel_holidays",["Flights"],["TRAVEL_AND_TRANSPORTATION_FLIGHTS"],{}),
("accommodation","travel_holidays",["Hotels and Accommodation","Hotels and Other Accomodation"],["TRAVEL_AND_TRANSPORTATION_LODGING"],{}),
("holiday_package","travel_holidays",["Holidays"],[],{}),
("holiday_uk","travel_holidays",["Holidays UK"],[],{}),
("holiday_rental","travel_holidays",["Holiday Cottages and Villas"],[],{}),
("camping_holiday","travel_holidays",["Camping Holidays"],[],{}),
("ferry_rail_travel","travel_holidays",["Ferries and Rail"],[],{}),
("airport_spend","travel_holidays",["Airport Spending","Duty Free"],[],{}),
("airport_parking","travel_holidays",["Airport Parking"],[],{}),
("foreign_currency","travel_holidays",["Foreign Currency","Foreign Currencies"],[],{}),
("foreign_spend_unspecified","travel_holidays",["Foreign"],[],{"n":"mixed_basket"}),
("luggage_travel_goods","travel_holidays",["Travel Guides, Luggage And Accessories"],[],{}),
("travel_other","travel_holidays",["Other Travel","primary:Flights and Holidays"],[],{}),
# ---- ENTERTAINMENT
("gaming_console_pc","entertainment_leisure",["PC and Console Games"],[],{}),
("gaming_mobile","entertainment_leisure",["Mobile Games","Mobile Apps and Games"],[],{"w":"microtransactions can proxy compulsive spend"}),
("gaming_online","entertainment_leisure",["Online Games"],[],{}),
("cinema","entertainment_leisure",["Cinema"],[],{}),
("live_music","entertainment_leisure",["Music Tickets"],["ENTERTAINMENT_EVENTS_AND_TICKETS"],{}),
("theatre","entertainment_leisure",["Theatre Tickets"],[],{}),
("sports_tickets","entertainment_leisure",["Sports Ticket"],[],{}),
("sports_participation","entertainment_leisure",["Sporting General"],[],{}),
("sports_equipment","entertainment_leisure",["Sports Equipment"],[],{}),
("camping_equipment","entertainment_leisure",["Camping Equipment"],[],{}),
("days_out","entertainment_leisure",["Days Out"],[],{}),
("experience_days","entertainment_leisure",["Experience Days"],[],{}),
("event_planning","entertainment_leisure",["Event Planning"],[],{}),
("books","entertainment_leisure",["General Books","primary:Books, Newspapers and Magazines"],[],{}),
("newspapers","entertainment_leisure",["Newspapers"],[],{}),
("magazines","entertainment_leisure",["Magazines"],[],{}),
("comics","entertainment_leisure",["Comic Books"],[],{}),
("physical_media","entertainment_leisure",["DVD and Blu-ray"],[],{}),
("music_other","entertainment_leisure",["Music"],[],{}),
("musical_instruments","entertainment_leisure",["Musical Instruments"],[],{}),
("arts_crafts","entertainment_leisure",["Art and Craft"],[],{}),
("games_puzzles","entertainment_leisure",["Games and Puzzles"],[],{}),
("memberships","entertainment_leisure",["General Memberships"],[],{}),
("private_members_club","entertainment_leisure",["Private Members Club"],[],{}),
("adult_entertainment","entertainment_leisure",["Adult Entertainment"],[],{"a":"true"}),
("adult_products","entertainment_leisure",["Over 18 Toys"],[],{"a":"true"}),
("entertainment_other","entertainment_leisure",["General Entertainment","primary:Entertainment"],["ENTERTAINMENT_OTHER_ENTERTAINMENT","ENTERTAINMENT_MUSIC_VIDEO_GAMES_TV_AND_MOVIES"],{"w":"Plaid bundles streaming+games+cinema here - real signal loss"}),
# ---- DIGITAL SUBS
("streaming","digital_subscriptions_services",["Music and Downloads"],[],{"w":"ALL consumer media streaming, video and music alike (Netflix, Spotify, Prime Video, Now TV)"}),
("software","digital_subscriptions_services",["Software"],[],{}),
("web_services","digital_subscriptions_services",["Web Services"],[],{"w":"technical/infrastructure services: hosting, domains, VPN, cloud, developer tools"}),
("online_services","digital_subscriptions_services",["Online Services"],[],{"w":"consumer-facing digital platforms: social, creator and content services (TikTok, Facebook, Patreon)"}),
("email_services","digital_subscriptions_services",["Email Services"],[],{}),
("online_dating","digital_subscriptions_services",["Online Dating"],[],{"a":"true"}),
("genealogy_services","digital_subscriptions_services",["Family History"],[],{}),
("social_reporting","digital_subscriptions_services",["Social Reporting Services"],[],{}),
# ---- HEALTH
("pharmacy","health_medical",["Pharmaceuticals"],["MEDICAL_PHARMACIES_AND_SUPPLEMENTS"],{"w":"pharmacy-led health retail (Boots, Superdrug) even where partly beauty; beauty-led retail without a pharmacy identity is health_beauty_general"}),
("medicine","health_medical",["Medicine"],[],{}),
("supplements","health_medical",["Supplements"],[],{"n":"discretionary"}),
("dentist","health_medical",["Dentist"],[],{}),
("optician","health_medical",["Glasses and Contact Lenses"],["MEDICAL_DENTAL_AND_VISION"],{}),
("hospital","health_medical",["Hospitals"],["MEDICAL_PRIMARY_CARE"],{}),
("mental_health_services","health_medical",["Counselling and Mental Health"],[],{"w":"vulnerability-relevant"}),
("gym_fitness","health_medical",["Gyms And Health Clubs"],["PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS"],{"n":"discretionary"}),
("weight_loss","health_medical",["Weight Loss"],[],{"n":"discretionary"}),
("adult_care","health_medical",["Adult Care"],[],{}),
("family_services","health_medical",["Family Services"],[],{}),
("funeral","health_medical",["Funeral Directors"],[],{"w":"life-event signal"}),
("health_other","health_medical",["primary:Personal Healthcare","Medical"],["MEDICAL_OTHER_MEDICAL"],{}),
# ---- INSURANCE
("insurance_general","insurance",["General Insurance","primary:Insurance"],["INSURANCE_AND_TAX_INSURANCE"],{"w":"multi-line insurers (Admiral, Legal & General) and unidentifiable insurance"}),
("insurance_motor","insurance",["Motor Insurance"],[],{"w":"motor-specific brands only (Swiftcover); multi-line insurers are insurance_general"}),
("insurance_home","insurance",["Home Insurance"],[],{}),
("insurance_life","insurance",["Life Insurance"],[],{}),
("insurance_health","insurance",["Health Insurance"],[],{}),
("insurance_travel","insurance",["Travel Insurance"],[],{"n":"discretionary"}),
("insurance_other","insurance",["Other Insurance"],[],{}),
# ---- CREDIT
("credit_card_repayment","credit_loan_repayments",["Credit Cards"],["LOAN_PAYMENTS_CREDIT_CARD_PAYMENT"],{"d":"true"}),
("charge_card_repayment","credit_loan_repayments",["Charge Card"],[],{"d":"true"}),
("revolving_credit_repayment","credit_loan_repayments",["Revolving Credit"],[],{"d":"true"}),
("personal_loan_repayment","credit_loan_repayments",["Personal Loans","primary:Loans"],["LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT"],{"d":"true"}),
("student_loan_repayment","credit_loan_repayments",[],["LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT"],{"d":"true","w":"no Equifax equivalent"}),
("car_finance_repayment","credit_loan_repayments",["Car Finance"],[],{"d":"true"}),
("car_lease","credit_loan_repayments",["Car Lease Plan"],[],{"d":"true"}),
("hire_purchase_repayment","credit_loan_repayments",["Hire Purchase"],[],{"d":"true"}),
("retail_finance_repayment","credit_loan_repayments",["Retail Finance"],[],{"d":"true","w":"closest analogue to Raylo's own product"}),
("bnpl","credit_loan_repayments",["BNPL"],["LOAN_PAYMENTS_BNPL_AND_EWA"],{"d":"true","r":"high_cost_credit"}),
("credit_union_repayment","credit_loan_repayments",["Credit Unions"],[],{"d":"true"}),
("balance_transfer","credit_loan_repayments",["primary:Balance Transfers"],[],{"d":"true"}),
("loan_repayment_manual","credit_loan_repayments",["Manual Repayment"],[],{"d":"true"}),
("loan_repayment_dd","credit_loan_repayments",["Direct Debit Repayments"],[],{"d":"true"}),
("loan_disbursement","credit_loan_repayments",[],["LOAN_DISBURSEMENTS_OTHER","LOAN_DISBURSEMENTS_PERSONAL","LOAN_DISBURSEMENTS_STUDENT","LOAN_DISBURSEMENTS_MORTGAGE_AND_AUTO","LOAN_DISBURSEMENTS_BNPL_AND_EWA"],{"d":"true","c":"debt_disbursement","n":"not_applicable","w":"no Equifax equivalent - borrowing inflow"}),
("financial_services_other","credit_loan_repayments",["Financial Services Other","primary:Financial Services"],["GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_SERVICES"],{"n":"mixed_basket","c":"spend"}),
("loan_repayment_other","credit_loan_repayments",[],["LOAN_PAYMENTS_OTHER"],{"d":"true"}),
# ---- HIGH COST & DISTRESS
("payday_loan","high_cost_distress_credit",["Payday Loans"],[],{"d":"true","r":"high_cost_credit"}),
("pawnbroker","high_cost_distress_credit",["Pawn Brokers"],[],{"d":"true","r":"high_cost_credit"}),
("cash_advance","high_cost_distress_credit",[],["LOAN_PAYMENTS_CASH_ADVANCES","LOAN_DISBURSEMENTS_CASH_ADVANCES"],{"d":"true","r":"high_cost_credit"}),
("cash_advance_fee","high_cost_distress_credit",["Cash Advance Fees"],[],{"c":"fee_or_penalty","n":"not_applicable","r":"distress_fee"}),
("debt_collection","high_cost_distress_credit",["Debt Collection"],[],{"d":"true","r":"distress_signal"}),
("debt_enforcement","high_cost_distress_credit",["Marston Holdings"],[],{"d":"true","r":"distress_signal","w":"bailiff/enforcement - MORE SEVERE than debt collection"}),
("debt_management_plan","high_cost_distress_credit",["Debt Management"],[],{"d":"true","r":"distress_signal"}),
("overdraft_unarranged","high_cost_distress_credit",["Unarranged Overdraft"],[],{"c":"fee_or_penalty","n":"not_applicable","r":"distress_fee","w":"only 126 txns in Equifax but the GENUINE distress marker"}),
("account_misuse","high_cost_distress_credit",["Account Misuse"],[],{"c":"fee_or_penalty","n":"not_applicable","r":"distress_signal"}),
("credit_reporting_service","high_cost_distress_credit",["Budgeting and Credit Reporting Services"],[],{"c":"spend","n":"discretionary","r":"distress_signal"}),
("money_management_service","high_cost_distress_credit",["Money Management"],[],{"c":"spend","n":"discretionary","r":"distress_signal"}),
# ---- GAMBLING
("gambling_betting","gambling",["Betting"],[],{"r":"behavioural_risk","a":"true","w":"FREQUENCY form not persistence"}),
("gambling_casino","gambling",["Poker and Casino Games"],[],{"r":"behavioural_risk","a":"true"}),
("gambling_bingo","gambling",["Bingo"],[],{"r":"behavioural_risk","a":"true"}),
("gambling_lottery","gambling",["Lottery"],[],{"r":"low_stakes_gambling","a":"true","w":"licensed lotteries only (National Lottery, Postcode Lottery); prize-draw platforms are prize_competitions. HIGHEST-IV gambling subtype 0.0498 - do not aggregate"}),
("prize_competitions","gambling",["Competitions"],[],{"r":"low_stakes_gambling","a":"true","w":"prize-draw competition platforms (Omaze, BOTB) - gambling-adjacent, not licensed lottery"}),
("gambling_unspecified","gambling",["primary:Gambling and Betting"],["ENTERTAINMENT_CASINOS_AND_GAMBLING"],{"r":"behavioural_risk","a":"true","w":"Plaid has no gambling subtypes"}),
# ---- FEES
("overdraft_arranged","fees_charges",["Arranged Overdraft"],["BANK_PENALTIES_CASH_ADVANCE_AND_OVERDRAFT_FEES"],{"d":"true","w":"NOT distress - arranged overdraft is a normal product, IV 0.0033"}),
("returned_payment","fees_charges",["Returned Payments","Rejected Payments"],["BANK_PENALTIES_INSUFFICIENT_AND_LATE_FEES"],{"r":"distress_fee","w":"count BOTH directions - mostly appears as credits"}),
("interest_charged","fees_charges",["Interest Charge","primary:Interest Payments"],["INTEREST_PAYMENTS_INTEREST_CHARGED"],{"d":"true"}),
("account_charge","fees_charges",["Account Charges"],["BANK_FEES_OTHER_BANK_FEES","BANK_FEES_ATM","BANK_FEES_FOREIGN_TRANSACTION_FEES"],{}),
("credit_card_fee","fees_charges",["Credit Card Fees"],[],{"d":"true"}),
("balance_transfer_fee","fees_charges",["Balance Transfer Fees"],[],{"d":"true"}),
("money_transfer_fee","fees_charges",["Money Transfer Fees"],[],{}),
("bank_charge_other","fees_charges",["primary:Bank Charges and Returns"],[],{}),
# ---- SAVINGS & INVESTMENTS
("savings_transfer","savings_investments",["primary:Savings"],["TRANSFER_OUT_SAVINGS","TRANSFER_IN_SAVINGS"],{}),
("pension_contribution","savings_investments",["primary:Pension"],[],{}),
("investment_general","savings_investments",["Investments","primary:Investments and Trading"],["TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS","TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS"],{}),
("investment_trading","savings_investments",["Trading"],[],{}),
("wealth_management","savings_investments",["Wealth Management"],[],{}),
("crypto","savings_investments",["Cryptocurrency"],[],{"r":"speculative_asset"}),
("forex_trading","savings_investments",["Forex"],[],{"r":"speculative_asset"}),
# ---- TRANSFERS
("transfer_own_account","transfers",["primary:Own Transfers"],["TRANSFER_OUT_CHECKING","TRANSFER_IN_CHECKING"],{}),
("transfer_p2p","transfers",["Transfer Personal"],["TRANSFER_OUT_TRANSFER_OUT_FROM_APPS","TRANSFER_IN_TRANSFER_IN_FROM_APPS"],{"c":"p2p_transfer","w":"possible informal borrowing"}),
("transfer_mobile_app","transfers",["Transfer Mobile App"],[],{"c":"p2p_transfer"}),
("transfer_bank_unspecified","transfers",["Bank Transfer"],[],{"w":"6.5M txns - mechanism known, purpose unknown; ML target"}),
("transfer_international","transfers",["International Transfer"],[],{"c":"p2p_transfer","w":"regular international transfers may indicate remittance commitment"}),
("money_transfer_service","transfers",["Money Transfers"],[],{"c":"p2p_transfer"}),
("prepaid_card","transfers",["Prepaid Cards"],[],{"w":"may indicate unbanked/thin-file behaviour"}),
("cheque","transfers",["Cheques"],[],{}),
("card_payment_unspecified","transfers",["Card Payment"],[],{}),
# ---- CASH
("cash_withdrawal","cash",["primary:Cash Machine"],["TRANSFER_OUT_CHECKS_AND_ATM"],{"r":"visibility_loss","w":"FREQUENCY form; downstream spend unobservable"}),
("cash_deposit","cash",["primary:Cash Deposit"],["TRANSFER_IN_CHECKS_AND_ATM"],{"r":"visibility_loss"}),
# ---- CHILDCARE & EDUCATION
("childcare","childcare_education",["Childcare"],["CHILDCARE_AND_EDUCATION_CHILDCARE_AND_EDUCATION"],{}),
("education_general","childcare_education",["General Education","primary:Education and Learning"],[],{}),
("school_fees","childcare_education",["School Fees"],[],{}),
("home_learning","childcare_education",["Home Learning"],[],{}),
("driving_tuition","childcare_education",["Driving Tuition"],[],{"n":"discretionary"}),
("career_services","childcare_education",["Career Services"],[],{"n":"discretionary"}),
# ---- PETS
("pet_supplies","pets",["Pet Accessories"],["PET_CARE_AND_SUPPLIES_PET_SUPPLIES"],{}),
("veterinary","pets",["Pet Care"],["PET_CARE_AND_SUPPLIES_VETERINARY_SERVICES"],{"n":"essential"}),
("insurance_pet","pets",["Pet Insurance"],[],{}),
("pet_other","pets",["primary:Pets"],[],{}),
# ---- CHARITY & POLITICAL
("charitable_donation","charitable_political_giving",["primary:Charitable Giving"],["GOVERNMENTS_AND_NON_PROFIT_DONATIONS","GENERAL_SERVICES_RELIGIOUS_SERVICES"],{}),
("charity_shop","charitable_political_giving",["Charity Shops"],[],{}),
("political_donation","charitable_political_giving",["Political Parties"],[],{}),
# ---- BUSINESS & SELF-EMPLOYMENT
("business_services","business_self_employment",["Business Services","Contract Services"],["GENERAL_SERVICES_OTHER_SERVICES"],{}),
("it_services","business_self_employment",["IT Services"],[],{}),
("accountancy","business_self_employment",["Accountancy"],[],{}),
("legal_services","business_self_employment",["Legal Services"],["GENERAL_SERVICES_CONSULTING_AND_LEGAL_SERVICES"],{"w":"mixed personal/business use"}),
("advertising_services","business_self_employment",["Advertising Services"],[],{}),
("printing_services","business_self_employment",["Printing"],[],{}),
("photography_services","business_self_employment",["Photography Services"],[],{}),
("office_supplies","business_self_employment",["Office Supplies"],[],{}),
("office_equipment","business_self_employment",["Office Equipment","Office Electricals"],[],{}),
("business_loan_repayment","business_self_employment",["Business Loans"],[],{"d":"true","c":"debt_repayment","n":"essential"}),
("trade_union","business_self_employment",["Trade Unions"],[],{}),
# ---- UNCLASSIFIED
("unclassified_recurring","unclassified",["primary:Misc Regular Payments"],[],{"w":"TOP PREDICTOR IV 0.1813 and unnamed - highest-value ML target"}),
("unclassified_card_spend","unclassified",["primary:Misc Card Spend"],[],{"w":"6.2M txns, 95% prevalence - ML target"}),
("unclassified_transfer","unclassified",["primary:Transfers / Other"],["TRANSFER_OUT_OTHER","TRANSFER_IN_OTHER"],{"w":"9.6M txns - largest single bucket"}),
("financial_institution_unspecified","unclassified",["Banks And Building Societies"],[],{"w":"302k txns; Equifax files mortgage lenders here - needs merchant resolution"}),
("services_unspecified","unclassified",["primary:Services","General"],[],{}),
("adjustment","unclassified",["primary:Adjustments"],[],{}),
("unclassified_other","unclassified",["primary:(null)","primary:Misc"],["OTHER_OTHER"],{}),
]

rows=[]
for det,gen,eqx,plaid,o in L:
    n,c = D[gen]
    rows.append({
      "detailed_category":det,"general_category":gen,
      "necessity":o.get("n",n),"cash_flow_type":o.get("c",c),
      "is_debt_related":o.get("d","false"),"is_priority_debt":o.get("p","false"),
      "is_age_restricted":o.get("a","false"),"risk_flag":o.get("r","none"),
      "is_recurring_income":"true" if o.get("o")=="recurring_income" else "",
      "equifax_source":" ; ".join(eqx),"plaid_source":" ; ".join(plaid),
      "notes":o.get("w","")})

fn=["detailed_category","general_category","necessity","cash_flow_type","is_debt_related",
"is_priority_debt","is_age_restricted","risk_flag","is_recurring_income","equifax_source","plaid_source","notes"]
with open("../taxonomy/taxonomy.csv","w",newline="") as f:
    w=csv.DictWriter(f,fieldnames=fn); w.writeheader(); w.writerows(rows)
print("detailed leaves:",len(rows))
print("generals used:",len(set(r['general_category'] for r in rows)),"of",len(GENERALS))
missing=[g for g in GENERALS if g not in set(r['general_category'] for r in rows)]
print("generals with no leaves:",missing)
dupes=[d for d in set(r['detailed_category'] for r in rows) if [r['detailed_category'] for r in rows].count(d)>1]
print("duplicate leaf names:",dupes)
