
-- ============ RAYLO UNIFIED TAXONOMY - crosswalk application (sample test) ============
-- Precedence waterfall (CLAUDE.md section 4): T1 direction overrides -> T2 compound rules ->
-- T3 mechanism-override primaries -> T4 merchant dictionary -> T5 deterministic rules ->
-- T6 provider crosswalk (fallback) -> T7 unclassified.
WITH sub_xw AS (SELECT * FROM UNNEST([STRUCT<eqx_sub STRING, leaf STRING>
    ('Account Charges','account_charge'),
    ('Account Misuse','account_misuse'),
    ('Accountancy','accountancy'),
    ('Adult Care','adult_care'),
    ('Adult Entertainment','adult_entertainment'),
    ('Advertising Services','advertising_services'),
    ('Airport Parking','airport_parking'),
    ('Airport Spending','airport_spend'),
    ('Alcoholic Beverages Beers and Spirits','alcohol_beer_spirits'),
    ('Alcoholic Beverages Wines','alcohol_wine'),
    ('Amazon','marketplace_amazon'),
    ('Arranged Overdraft','overdraft_arranged'),
    ('Art and Craft','arts_crafts'),
    ('Audio Equipment','audio_equipment'),
    ('BNPL','bnpl'),
    ('Baby Gifts','baby_products'),
    ('Back Market Uk Ltd','marketplace_refurbished'),
    ('Balance Transfer Fees','balance_transfer_fee'),
    ('Bank Interest Accrual','savings_interest_received'),
    ('Bank Transfer','transfer_bank_unspecified'),
    ('Banks And Building Societies','financial_institution_unspecified'),
    ('Bathroom Furniture and Accessories','bathroom'),
    ('Beauty & Massage','beauty_treatment'),
    ('Bedding','bedding'),
    ('Betting','gambling_betting'),
    ('Bikes and Accessories','bicycle'),
    ('Bingo','gambling_bingo'),
    ('Breakdown Cover','breakdown_cover'),
    ('Budgeting and Credit Reporting Services','credit_reporting_service'),
    ('Business Loans','business_loan_repayment'),
    ('Business Services','business_services'),
    ('Cameras and Photography','camera_photography'),
    ('Camping Equipment','camping_equipment'),
    ('Camping Holidays','camping_holiday'),
    ('Car Dealerships','vehicle_purchase'),
    ('Car Finance','car_finance_repayment'),
    ('Car Lease Plan','car_lease'),
    ('Car Parking','car_parking'),
    ('Car Services','vehicle_servicing'),
    ('Card Payment','card_payment_unspecified'),
    ('Career Services','career_services'),
    ('Carwash','carwash'),
    ('Cash & Carry','cash_and_carry'),
    ('Cash Advance Fees','cash_advance_fee'),
    ('Cashback rewards','cashback'),
    ('Catering','catering'),
    ('Charge Card','charge_card_repayment'),
    ('Charity Shops','charity_shop'),
    ('Cheques','cheque'),
    ('Childcare','childcare'),
    ('Childrens Fashion','clothing_childrens'),
    ('Chip Shed Bourton Limited','takeaway'),
    ('Cinema','cinema'),
    ('Cleaning Services','cleaning_services'),
    ('Comic Books','comics'),
    ('Competitions','prize_competitions'),
    ('Computer Peripherals and Accessories','computer_peripherals'),
    ('Computers, Laptops and Tablets','computing_devices'),
    ('Confectionary','confectionary'),
    ('Construction','construction_services'),
    ('Contract Services','business_services'),
    ('Council','council_tax'),
    ('Counselling and Mental Health','mental_health_services'),
    ('Credit Card Fees','credit_card_fee'),
    ('Credit Cards','credit_card_repayment'),
    ('Credit Unions','credit_union_repayment'),
    ('Cryptocurrency','crypto'),
    ('DVD and Blu-ray','physical_media'),
    ('Days Out','days_out'),
    ('Debt Collection','debt_collection'),
    ('Debt Management','debt_management_plan'),
    ('Delivery','delivery_courier'),
    ('Dentist','dentist'),
    ('Department Stores','department_store'),
    ('Direct Debit Repayments','loan_repayment_dd'),
    ('Discount Stores','discount_store'),
    ('Dividend','dividend_received'),
    ('Driving Tuition','driving_tuition'),
    ('Duty Free','airport_spend'),
    ('E-Commerce Payment System','payment_intermediary'),
    ('Electronic Cigarettes','vaping'),
    ('Email Services','email_services'),
    ('Emergency Services','emergency_services'),
    ('Employee Rewards','employee_benefits'),
    ('Employment Agencies','income_agency_work'),
    ('Energy Providers','energy'),
    ('Estate Agents','estate_agent'),
    ('Event Planning','event_planning'),
    ('Experience Days','experience_days'),
    ('Fairtrade and ethical products','groceries_specialist'),
    ('Family History','genealogy_services'),
    ('Family Services','family_services'),
    ('Fancy Dress','fancy_dress'),
    ('Ferries and Rail','ferry_rail_travel'),
    ('Financial Services Other','financial_services_other'),
    ('Flights','flights'),
    ('Footwear','footwear'),
    ('Foreign','foreign_spend_unspecified'),
    ('Foreign Currencies','foreign_currency'),
    ('Foreign Currency','foreign_currency'),
    ('Forex','forex_trading'),
    ('Fragrances','fragrances'),
    ('Fuel','fuel'),
    ('Funeral Directors','funeral'),
    ('Gadgets and Gizmos','gadgets'),
    ('Games and Puzzles','games_puzzles'),
    ('Garages and Parts','vehicle_maintenance'),
    ('Garden Accessories','garden'),
    ('General','services_unspecified'),
    ('General Baby Products','baby_products'),
    ('General Books','books'),
    ('General Car Hire','car_hire'),
    ('General Catalogues','catalogue_retail'),
    ('General Education','education_general'),
    ('General Electrical','electrical_goods'),
    ('General Entertainment','entertainment_other'),
    ('General Fashion','clothing_general'),
    ('General Groceries','groceries'),
    ('General Health and Beauty','health_beauty_general'),
    ('General Insurance','insurance_general'),
    ('General Memberships','memberships'),
    ('Gifts Flowers and Parties','gifts_flowers'),
    ('Glasses and Contact Lenses','optician'),
    ('Government Services','government_services'),
    ('Gyms And Health Clubs','gym_fitness'),
    ('Health Insurance','insurance_health'),
    ('Heating Oil','heating_oil'),
    ('Hire Purchase','hire_purchase_repayment'),
    ('Holiday Cottages and Villas','holiday_rental'),
    ('Holidays','holiday_package'),
    ('Holidays UK','holiday_uk'),
    ('Home Accessories','home_accessories'),
    ('Home Improvements','home_improvement'),
    ('Home Insurance','insurance_home'),
    ('Home Learning','home_learning'),
    ('Hospitals','hospital'),
    ('Hotels and Accommodation','accommodation'),
    ('Hotels and Other Accomodation','accommodation'),
    ('Household Appliances','household_appliances'),
    ('Household Repair Services','home_repair'),
    ('Housing Benefits','housing_benefit'),
    ('ID Cards','id_documents'),
    ('IT Services','it_services'),
    ('Interest Charge','interest_charged'),
    ('International Transfer','transfer_international'),
    ('Internet, TV and Phone','broadband_tv_phone'),
    ('Investments','investment_general'),
    ('Ipswich 5 Star Ltd','takeaway'),
    ('Jewellery and Accesories','jewellery'),
    ('Kitchens and Kitchen Accessories','kitchen'),
    ('Laundry Services','laundry'),
    ('Legal Services','legal_services'),
    ('Life Insurance','insurance_life'),
    ('Lights and Lamps','lighting'),
    ('Lottery','gambling_lottery'),
    ('M.O.T.','vehicle_mot'),
    ('Magazines','magazines'),
    ('Manual Repayment','loan_repayment_manual'),
    ('Marston Holdings','debt_enforcement'),
    ('Maternity Clothing','clothing_maternity'),
    ('Medical','health_other'),
    ('Medicine','medicine'),
    ('Mens Fashion','clothing_mens'),
    ('Mobile Apps and Games','gaming_mobile'),
    ('Mobile Games','gaming_mobile'),
    ('Mobile Handsets and Accessories','mobile_handset'),
    ('Mobile Phone Contracts','mobile_phone_contract'),
    ('Money Management','money_management_service'),
    ('Money Transfer Fees','money_transfer_fee'),
    ('Money Transfers','money_transfer_service'),
    ('Mortgages','mortgage'),
    ('Motor Insurance','insurance_motor'),
    ('Music','music_other'),
    ('Music Tickets','live_music'),
    ('Music and Downloads','streaming'),
    ('Musical Instruments','musical_instruments'),
    ('Newsagents and Convenience Stores','convenience_store'),
    ('Newspapers','newspapers'),
    ('Night Clubs','night_club'),
    ('Office Electricals','office_equipment'),
    ('Office Equipment','office_equipment'),
    ('Office Supplies','office_supplies'),
    ('Online Dating','online_dating'),
    ('Online Games','gaming_online'),
    ('Online Services','online_services'),
    ('Other Insurance','insurance_other'),
    ('Other Travel','travel_other'),
    ('Outdoor Clothing','clothing_outdoor'),
    ('Over 18 Toys','adult_products'),
    ('PC and Console Games','gaming_console_pc'),
    ('Pawn Brokers','pawnbroker'),
    ('Payday Loans','payday_loan'),
    ('Personal Loans','personal_loan_repayment'),
    ('Pet Accessories','pet_supplies'),
    ('Pet Care','veterinary'),
    ('Pet Insurance','insurance_pet'),
    ('Pharmaceuticals','pharmacy'),
    ('Photography Services','photography_services'),
    ('Plants','garden'),
    ('Poker and Casino Games','gambling_casino'),
    ('Political Parties','political_donation'),
    ('Prepaid Cards','prepaid_card'),
    ('Printers, Printer Ink and Printer Toner','printing_supplies'),
    ('Printing','printing_services'),
    ('Private Members Club','private_members_club'),
    ('Property Management','property_management'),
    ('Property Rental','rent'),
    ('Pubs and Bars','pub_bar'),
    ('Recruitment Services','income_agency_work'),
    ('Recycling','waste_services'),
    ('Rejected Payments','returned_payment'),
    ('Restaurants, Cafes and Bistros','restaurant_cafe'),
    ('Retail Finance','retail_finance_repayment'),
    ('Returned Payments','returned_payment'),
    ('Revolving Credit','revolving_credit_repayment'),
    ('Road Tax','road_tax'),
    ('School Fees','school_fees'),
    ('Skin and Hair Care','skin_hair_care'),
    ('Small Retail','retail_small_independent'),
    ('Social Reporting Services','social_reporting'),
    ('Software','software'),
    ('Spares and Repairs','spares_repairs'),
    ('Sporting General','sports_participation'),
    ('Sports Equipment','sports_equipment'),
    ('Sports Ticket','sports_tickets'),
    ('Sportswear','sportswear'),
    ('Stationery','stationery'),
    ('Storage','storage'),
    ('Supplements','supplements'),
    ('TV Licences','tv_licence'),
    ('TV and Online Shopping','retail_tv_online_shopping'),
    ('Take Away','takeaway'),
    ('Taxis','taxi_rideshare'),
    ('Theatre Tickets','theatre'),
    ('Tobacco Products','tobacco'),
    ('Tolls and Crossings','tolls'),
    ('Tools','tools'),
    ('Toy Stores','toys'),
    ('Trade Unions','trade_union'),
    ('Tradesmen','tradesmen'),
    ('Trading','investment_trading'),
    ('Trains and Coaches','public_transport_rail_coach'),
    ('Transfer Mobile App','transfer_mobile_app'),
    ('Transfer Personal','transfer_p2p'),
    ('Travel Guides, Luggage And Accessories','luggage_travel_goods'),
    ('Travel Insurance','insurance_travel'),
    ('Unarranged Overdraft','overdraft_unarranged'),
    ('Vouchers/Discount Codes','vouchers'),
    ('Waste Services','waste_services'),
    ('Water Companies','water'),
    ('Wealth Management','wealth_management'),
    ('Web Services','web_services'),
    ('Weight Loss','weight_loss'),
    ('Womens Fashion','clothing_womens'),
    ('Workwear','clothing_workwear')
])),
pri_xw AS (SELECT * FROM UNNEST([STRUCT<eqx_pri STRING, leaf STRING>
    ('Adjustments','adjustment'),
    ('Amazon All','marketplace_amazon'),
    ('Automotive','transport_other'),
    ('Balance Transfers','balance_transfer'),
    ('Bank Charges and Returns','bank_charge_other'),
    ('Benefits','benefits_state'),
    ('Books, Newspapers and Magazines','books'),
    ('Cash Back','cashback'),
    ('Cash Deposit','cash_deposit'),
    ('Cash Machine','cash_withdrawal'),
    ('Charitable Giving','charitable_donation'),
    ('Commuting and travel','transport_other'),
    ('Education and Learning','education_general'),
    ('Entertainment','entertainment_other'),
    ('Financial Services','financial_services_other'),
    ('Flights and Holidays','travel_other'),
    ('Gambling and Betting','gambling_unspecified'),
    ('Government','government_services'),
    ('Identified Salary','salary'),
    ('Insurance','insurance_general'),
    ('Interest','savings_interest_received'),
    ('Interest Payments','interest_charged'),
    ('Interests and Dividends','savings_interest_received'),
    ('Investments and Trading','investment_general'),
    ('Loans','personal_loan_repayment'),
    ('Misc','unclassified_other'),
    ('Misc Card Spend','unclassified_card_spend'),
    ('Misc Regular Payments','unclassified_recurring'),
    ('Own Transfers','transfer_own_account'),
    ('Pension','pension_contribution'),
    ('Pension Payout','pension_received'),
    ('Personal Healthcare','health_other'),
    ('Pets','pet_other'),
    ('Refund','refund_received'),
    ('Rent and Mortgage','housing_other'),
    ('Restaurants and takeaway','eating_out_other'),
    ('Savings','savings_transfer'),
    ('Services','services_unspecified'),
    ('Shopping (Discretionary)','retail_other'),
    ('Shopping (Fashion)','retail_other'),
    ('Shopping (Home)','retail_other'),
    ('Shopping (Household Essentials)','retail_other'),
    ('Tax','tax_payment'),
    ('Tax Refund','tax_refund'),
    ('Transfers / Other','unclassified_transfer'),
    ('Utilities','utility_other'),
    ('Welfare','benefits_state')
])),
plaid_xw AS (SELECT * FROM UNNEST([STRUCT<plaid_cat STRING, leaf STRING>
    ('BANK_FEES_ATM','account_charge'),
    ('BANK_FEES_FOREIGN_TRANSACTION_FEES','account_charge'),
    ('BANK_FEES_OTHER_BANK_FEES','account_charge'),
    ('BANK_PENALTIES_CASH_ADVANCE_AND_OVERDRAFT_FEES','overdraft_arranged'),
    ('BANK_PENALTIES_INSUFFICIENT_AND_LATE_FEES','returned_payment'),
    ('CHILDCARE_AND_EDUCATION_CHILDCARE_AND_EDUCATION','childcare'),
    ('DINING_COFFEE','restaurant_cafe'),
    ('DINING_DINING','restaurant_cafe'),
    ('DINING_OTHER_DINING','restaurant_cafe'),
    ('DINING_WINE_BARS_AND_PUBS','pub_bar'),
    ('ENTERTAINMENT_CASINOS_AND_GAMBLING','gambling_unspecified'),
    ('ENTERTAINMENT_EVENTS_AND_TICKETS','live_music'),
    ('ENTERTAINMENT_MUSIC_VIDEO_GAMES_TV_AND_MOVIES','entertainment_other'),
    ('ENTERTAINMENT_OTHER_ENTERTAINMENT','entertainment_other'),
    ('FOOD_RETAIL_GROCERIES','groceries'),
    ('FOOD_RETAIL_LIQUOR_STORES','alcohol_beer_spirits'),
    ('FOOD_RETAIL_OTHER','groceries'),
    ('GENERAL_MERCHANDISE_APPAREL_AND_ACCESSORIES','clothing_general'),
    ('GENERAL_MERCHANDISE_COMPUTERS_AND_ELECTRONICS','computing_devices'),
    ('GENERAL_MERCHANDISE_CONVENIENCE_STORES','convenience_store'),
    ('GENERAL_MERCHANDISE_DEPARTMENT_STORES','department_store'),
    ('GENERAL_MERCHANDISE_DISCOUNT_STORES','discount_store'),
    ('GENERAL_MERCHANDISE_FURNITURE_AND_HARDWARE','home_accessories'),
    ('GENERAL_MERCHANDISE_ONLINE_MARKETPLACES','marketplace_general'),
    ('GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE','retail_other'),
    ('GENERAL_MERCHANDISE_SPORTING_GOODS','sportswear'),
    ('GENERAL_MERCHANDISE_SUPERSTORES','groceries'),
    ('GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_SERVICES','financial_services_other'),
    ('GENERAL_SERVICES_CONSULTING_AND_LEGAL_SERVICES','legal_services'),
    ('GENERAL_SERVICES_HOME_IMPROVEMENT_SERVICES','home_improvement'),
    ('GENERAL_SERVICES_OTHER_SERVICES','business_services'),
    ('GENERAL_SERVICES_RELIGIOUS_SERVICES','charitable_donation'),
    ('GOVERNMENTS_AND_NON_PROFIT_DONATIONS','charitable_donation'),
    ('GOVERNMENTS_AND_NON_PROFIT_GOVERNMENTS_AND_NON_PROFIT','council_tax'),
    ('GOVERNMENTS_AND_NON_PROFIT_OTHER_GOVERNMENTS_AND_NON_PROFIT','government_services'),
    ('INCOME_GOVERNMENT_INCOME','benefits_state'),
    ('INCOME_OTHER','income_other_unspecified'),
    ('INCOME_SALARY','salary'),
    ('INSURANCE_AND_TAX_INSURANCE','insurance_general'),
    ('INSURANCE_AND_TAX_TAX_PAYMENT','tax_payment'),
    ('INTERESTS_AND_DIVIDENDS_INTERESTS_AND_DIVIDENDS','savings_interest_received'),
    ('INTEREST_PAYMENTS_INTEREST_CHARGED','interest_charged'),
    ('INTEREST_PAYMENTS_INTEREST_RECEIVED','savings_interest_received'),
    ('LOAN_DISBURSEMENTS_BNPL_AND_EWA','loan_disbursement'),
    ('LOAN_DISBURSEMENTS_CASH_ADVANCES','cash_advance'),
    ('LOAN_DISBURSEMENTS_MORTGAGE_AND_AUTO','loan_disbursement'),
    ('LOAN_DISBURSEMENTS_OTHER','loan_disbursement'),
    ('LOAN_DISBURSEMENTS_PERSONAL','loan_disbursement'),
    ('LOAN_DISBURSEMENTS_STUDENT','loan_disbursement'),
    ('LOAN_PAYMENTS_BNPL_AND_EWA','bnpl'),
    ('LOAN_PAYMENTS_CASH_ADVANCES','cash_advance'),
    ('LOAN_PAYMENTS_CREDIT_CARD_PAYMENT','credit_card_repayment'),
    ('LOAN_PAYMENTS_MORTGAGE_AND_AUTO','mortgage'),
    ('LOAN_PAYMENTS_OTHER','loan_repayment_other'),
    ('LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT','personal_loan_repayment'),
    ('LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT','student_loan_repayment'),
    ('MEDICAL_DENTAL_AND_VISION','optician'),
    ('MEDICAL_OTHER_MEDICAL','health_other'),
    ('MEDICAL_PHARMACIES_AND_SUPPLEMENTS','pharmacy'),
    ('MEDICAL_PRIMARY_CARE','hospital'),
    ('OTHER_OTHER','unclassified_other'),
    ('PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS','gym_fitness'),
    ('PERSONAL_CARE_HAIR_AND_BEAUTY','skin_hair_care'),
    ('PERSONAL_CARE_OTHER_PERSONAL_CARE','health_beauty_general'),
    ('PET_CARE_AND_SUPPLIES_PET_SUPPLIES','pet_supplies'),
    ('PET_CARE_AND_SUPPLIES_VETERINARY_SERVICES','veterinary'),
    ('RENT_AND_UTILITIES_GAS_AND_ELECTRICITY','energy'),
    ('RENT_AND_UTILITIES_INTERNET_AND_CABLE','broadband_tv_phone'),
    ('RENT_AND_UTILITIES_OTHER_UTILITIES','utility_other'),
    ('RENT_AND_UTILITIES_RENT','rent'),
    ('RENT_AND_UTILITIES_TELECOMMUNICATIONS','mobile_phone_contract'),
    ('RENT_AND_UTILITIES_WATER','water'),
    ('TAX_REFUND_TAX_REFUND','tax_refund'),
    ('TRANSFER_IN_CHECKING','transfer_own_account'),
    ('TRANSFER_IN_CHECKS_AND_ATM','cash_deposit'),
    ('TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS','investment_general'),
    ('TRANSFER_IN_OTHER','unclassified_transfer'),
    ('TRANSFER_IN_SAVINGS','savings_transfer'),
    ('TRANSFER_IN_TRANSFER_IN_FROM_APPS','transfer_p2p'),
    ('TRANSFER_OUT_CHECKING','transfer_own_account'),
    ('TRANSFER_OUT_CHECKS_AND_ATM','cash_withdrawal'),
    ('TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS','investment_general'),
    ('TRANSFER_OUT_OTHER','unclassified_transfer'),
    ('TRANSFER_OUT_SAVINGS','savings_transfer'),
    ('TRANSFER_OUT_TRANSFER_OUT_FROM_APPS','transfer_p2p'),
    ('TRAVEL_AND_TRANSPORTATION_AUTOMOTIVE','vehicle_maintenance'),
    ('TRAVEL_AND_TRANSPORTATION_FLIGHTS','flights'),
    ('TRAVEL_AND_TRANSPORTATION_LODGING','accommodation'),
    ('TRAVEL_AND_TRANSPORTATION_OTHER_TRAVEL_AND_TRANSPORTATION','transport_other'),
    ('TRAVEL_AND_TRANSPORTATION_PUBLIC_TRANSIT','public_transport_rail_coach'),
    ('TRAVEL_AND_TRANSPORTATION_TAXIS_AND_RIDE_SHARES','taxi_rideshare')
])),
dict_xw AS (SELECT * FROM UNNEST([STRUCT<merchant STRING, leaf STRING>
    ('118 money','payday_loan'),
    ('32 red online casino','gambling_casino'),
    ('888 games','gambling_casino'),
    ('a & s outdoor ltd','clothing_outdoor'),
    ('a&f bargains ltd','discount_store'),
    ('aa','breakdown_cover'),
    ('admiral insurance','insurance_motor'),
    ('adobe','software'),
    ('aldi','groceries'),
    ('aliexpress','marketplace_general'),
    ('all that falafel','takeaway'),
    ('amazon','marketplace_amazon'),
    ('amazon prime video','streaming'),
    ('american express','credit_card_repayment'),
    ('ancoats general store','convenience_store'),
    ('anglian water','water'),
    ('animal friends insurance','insurance_pet'),
    ('ann summers','adult_products'),
    ('anyvan','delivery_courier'),
    ('apcoa parking','car_parking'),
    ('apple','software'),
    ('apple app store','software'),
    ('apple store gb','computing_devices'),
    ('applegreen','fuel'),
    ('aqua','credit_card_repayment'),
    ('argos','catalogue_retail'),
    ('arriva','public_transport_rail_coach'),
    ('arsenal fc','sports_tickets'),
    ('asda','groceries'),
    ('asda (petrol)','fuel'),
    ('asos','clothing_general'),
    ('atlassian','software'),
    ('audible','streaming'),
    ('autotrader','advertising_services'),
    ('avg','software'),
    ('aviva','insurance_general'),
    ('aviva li','insurance_life'),
    ('b&m','discount_store'),
    ('b&q (diy.com)','home_improvement'),
    ('back market uk ltd','marketplace_refurbished'),
    ('bandcamp','music_other'),
    ('banquet records','physical_media'),
    ('barclaycard','credit_card_repayment'),
    ('barclays','financial_institution_unspecified'),
    ('barclays partner finance','retail_finance_repayment'),
    ('bargain booze','alcohol_beer_spirits'),
    ('base london','footwear'),
    ('beauty outlet','health_beauty_general'),
    ('berghaus','clothing_outdoor'),
    ('beryl','bicycle'),
    ('best meat','groceries_specialist'),
    ('best-one','groceries'),
    ('bestway','cash_and_carry'),
    ('bet365','gambling_betting'),
    ('betfair','gambling_betting'),
    ('betfred','gambling_betting'),
    ('betuk','gambling_casino'),
    ('betvictor','gambling_betting'),
    ('betway','gambling_betting'),
    ('bh live tickets','live_music'),
    ('bolt','taxi_rideshare'),
    ('bonmarche','clothing_womens'),
    ('boohoo','clothing_general'),
    ('booking.com','accommodation'),
    ('boots','pharmacy'),
    ('botb','prize_competitions'),
    ('boux avenue','clothing_womens'),
    ('boylesports','gambling_betting'),
    ('bp','fuel'),
    ('brass monkey','pub_bar'),
    ('bravissimo','clothing_womens'),
    ('british gas','energy'),
    ('british heart foundation','charity_shop'),
    ('brittany ferries','ferry_rail_travel'),
    ('bt','broadband_tv_phone'),
    ('budgens','groceries'),
    ('burger king','takeaway'),
    ('burton','clothing_general'),
    ('butlers bingo','gambling_bingo'),
    ('buzz group ltd','gambling_bingo'),
    ('cabot','debt_collection'),
    ('caffe nero','restaurant_cafe'),
    ('canva','software'),
    ('capital one','credit_card_repayment'),
    ('card factory','gifts_flowers'),
    ('carers allowance','benefits_state'),
    ('carrefour','groceries'),
    ('castle bingo','gambling_bingo'),
    ('center parcs','holiday_uk'),
    ('centra','groceries'),
    ('central convenience stores','convenience_store'),
    ('central england co-op','groceries'),
    ('cex','computing_devices'),
    ('char.gy','fuel'),
    ('charlotte tilbury','skin_hair_care'),
    ('child benefits','benefits_state'),
    ('child maintenance','income_other_unspecified'),
    ('child tax credit','benefits_state'),
    ('chip shed bourton limited','takeaway'),
    ('cineworld','cinema'),
    ('citylink','public_transport_rail_coach'),
    ('clarks','footwear'),
    ('clearpay','bnpl'),
    ('click competitions','prize_competitions'),
    ('co-op','groceries'),
    ('coinbase','crypto'),
    ('competition fox','prize_competitions'),
    ('corgi homeplan','insurance_home'),
    ('cosmetix limited','health_beauty_general'),
    ('costa','restaurant_cafe'),
    ('costco','groceries'),
    ('costcutter','groceries'),
    ('craft gin club','alcohol_beer_spirits'),
    ('creation online','retail_finance_repayment'),
    ('creditspring','payday_loan'),
    ('crocs','footwear'),
    ('cross foxes','pub_bar'),
    ('crunchyroll','streaming'),
    ('current','unclassified_other'),
    ('currys','computing_devices'),
    ('daniel footwear','footwear'),
    ('dawat-e-islami uk','charitable_donation'),
    ('debit finance','unclassified_other'),
    ('deezer','streaming'),
    ('deichmann','footwear'),
    ('delikatesy smaczek','groceries_specialist'),
    ('deliveroo','takeaway'),
    ('depop','marketplace_amazon'),
    ('disability living allowance','benefits_state'),
    ('discovery cove','days_out'),
    ('disney plus','streaming'),
    ('domestic and general','insurance_general'),
    ('dominos pizza','takeaway'),
    ('double bubble bingo','gambling_bingo'),
    ('dr martens','footwear'),
    ('dune','footwear'),
    ('dunelm','home_accessories'),
    ('dvla','road_tax'),
    ('e','unclassified_other'),
    ('e.leclerc','groceries'),
    ('e.on','energy'),
    ('east of england co-op','groceries'),
    ('easyjet','flights'),
    ('easyjet holidays','holiday_package'),
    ('ebay','marketplace_general'),
    ('edf','energy'),
    ('ee mobile','mobile_phone_contract'),
    ('electraworks limit','gambling_casino'),
    ('elemis','skin_hair_care'),
    ('ellis brigham','clothing_outdoor'),
    ('emigrantas tv','streaming'),
    ('emmaus','charity_shop'),
    ('employment and support allowance','benefits_state'),
    ('escentual','fragrances'),
    ('esso','fuel'),
    ('etsy','marketplace_general'),
    ('euphorium bakery','restaurant_cafe'),
    ('euro car parts','spares_repairs'),
    ('europa delikatesy','groceries_specialist'),
    ('express chemist','pharmacy'),
    ('extracare','charitable_donation'),
    ('facebook','online_services'),
    ('falafel stop','takeaway'),
    ('farmfoods','groceries'),
    ('feel good contacts','optician'),
    ('findmeagift','gifts_flowers'),
    ('first bus','public_transport_rail_coach'),
    ('flair afro cosmetics','skin_hair_care'),
    ('flannels','clothing_general'),
    ('foodhub','takeaway'),
    ('freemans','catalogue_retail'),
    ('freetrade','investment_trading'),
    ('fruugo','marketplace_amazon'),
    ('george at asda','clothing_general'),
    ('giffgaff.com','mobile_phone_contract'),
    ('gift company','gifts_flowers'),
    ('global exchange','foreign_currency'),
    ('glossybox','health_beauty_general'),
    ('go north east','public_transport_rail_coach'),
    ('go outdoors','clothing_outdoor'),
    ('go south coast','public_transport_rail_coach'),
    ('gocardless','payment_intermediary'),
    ('gohenry','prepaid_card'),
    ('google','software'),
    ('google play','software'),
    ('grab-a-bite','takeaway'),
    ('greene king','pub_bar'),
    ('greensquareaccord','rent'),
    ('greggs','restaurant_cafe'),
    ('grosvenor casinos','gambling_casino'),
    ('gumtree','marketplace_amazon'),
    ('h&m','clothing_general'),
    ('habitat','home_accessories'),
    ('halfords','vehicle_maintenance'),
    ('halifax','financial_institution_unspecified'),
    ('harvey nichols','department_store'),
    ('hastings direct','insurance_motor'),
    ('haven holidays','holiday_uk'),
    ('hayu','streaming'),
    ('health express','pharmacy'),
    ('herbalife','supplements'),
    ('heron foods','groceries'),
    ('hm revenue and customs','tax_payment'),
    ('hmrc','tax_payment'),
    ('hmv','physical_media'),
    ('holland & barrett','supplements'),
    ('home bargains','discount_store'),
    ('home group','rent'),
    ('home retail','catalogue_retail'),
    ('hotel chocolat','confectionary'),
    ('housing benefits','benefits_state'),
    ('hsbc','financial_institution_unspecified'),
    ('huel','groceries_specialist'),
    ('iceland','groceries'),
    ('id mobile','mobile_phone_contract'),
    ('ideal world','retail_tv_online_shopping'),
    ('ikea','home_accessories'),
    ('infinity foods','groceries_specialist'),
    ('interactive investor','investment_trading'),
    ('iss food','catering'),
    ('j d sport','sportswear'),
    ('jackpot joy','gambling_bingo'),
    ('jagex','gaming_online'),
    ('jd sports','sportswear'),
    ('jd williams','catalogue_retail'),
    ('jigsaw homes','rent'),
    ('jin bo law uk limited','legal_services'),
    ('just drinks 4u uk ltd','alcohol_beer_spirits'),
    ('just eat','takeaway'),
    ('kcom','broadband_tv_phone'),
    ('keystore','groceries'),
    ('kfc','takeaway'),
    ('kickers','footwear'),
    ('kilted competition','prize_competitions'),
    ('klarna','bnpl'),
    ('knickerbox','clothing_womens'),
    ('lacoste','clothing_general'),
    ('ladbrokes','gambling_betting'),
    ('lavazza professional','confectionary'),
    ('laybuy','bnpl'),
    ('lc international','gambling_betting'),
    ('leasys uk ltd','car_lease'),
    ('lebara','mobile_phone_contract'),
    ('legal & general','insurance_life'),
    ('lendable','personal_loan_repayment'),
    ('lending stream','payday_loan'),
    ('leon','restaurant_cafe'),
    ('lidl','groceries'),
    ('lightinthebox','retail_tv_online_shopping'),
    ('lily\'s kitchen','pet_supplies'),
    ('livecareer','career_services'),
    ('livescore bet','gambling_betting'),
    ('lloyds','financial_institution_unspecified'),
    ('londis','groceries'),
    ('lookfantastic','health_beauty_general'),
    ('loqbox','savings_transfer'),
    ('lothian buses','public_transport_rail_coach'),
    ('lotto land','gambling_lottery'),
    ('loveholidays.com','holiday_package'),
    ('lowell financial','debt_collection'),
    ('mainline menswear','clothing_mens'),
    ('mangopay','payment_intermediary'),
    ('marisota','clothing_womens'),
    ('marketplace','marketplace_general'),
    ('marks & spencer','department_store'),
    ('marks and spencer','department_store'),
    ('marks and spencer food','groceries'),
    ('marquess of anglesey','pub_bar'),
    ('martin mccoll','convenience_store'),
    ('matalan','clothing_general'),
    ('mcafee','software'),
    ('mcdonald\'s','takeaway'),
    ('mcdonalds','takeaway'),
    ('mcqueens dairies','groceries_specialist'),
    ('mecca bingo','gambling_bingo'),
    ('mercato metropolitano','restaurant_cafe'),
    ('microsoft','software'),
    ('mipermit','car_parking'),
    ('mircosoft','software'),
    ('missguided','clothing_womens'),
    ('mojang','gaming_console_pc'),
    ('moneybox','savings_transfer'),
    ('monopoly casino','gambling_casino'),
    ('monzo','transfer_own_account'),
    ('monzo flex','bnpl'),
    ('moonpig','gifts_flowers'),
    ('moorcroft debt recovery','debt_collection'),
    ('morrisons','groceries'),
    ('morrisons (petrol)','fuel'),
    ('motor fuel group','fuel'),
    ('mountain warehouse','clothing_outdoor'),
    ('mrq','gambling_casino'),
    ('nandos','restaurant_cafe'),
    ('national express','public_transport_rail_coach'),
    ('nationwide','financial_institution_unspecified'),
    ('natwest','financial_institution_unspecified'),
    ('ncp','car_parking'),
    ('netflix','streaming'),
    ('new balance','sportswear'),
    ('new look','clothing_general'),
    ('newday limited','credit_card_repayment'),
    ('next','clothing_general'),
    ('next directory','catalogue_retail'),
    ('nike','sportswear'),
    ('nintendo','gaming_console_pc'),
    ('nisa','groceries'),
    ('now tv','streaming'),
    ('o2','mobile_phone_contract'),
    ('octopus energy','energy'),
    ('odeon','cinema'),
    ('office shoes','footwear'),
    ('ogmore valley store ltd','convenience_store'),
    ('omaze','prize_competitions'),
    ('one stop','groceries'),
    ('onebelow','discount_store'),
    ('online carpets','home_accessories'),
    ('onlyfans','adult_entertainment'),
    ('overpayments','income_other_unspecified'),
    ('ovo energy','energy'),
    ('pactcoffee','groceries_specialist'),
    ('paddy power','gambling_betting'),
    ('palmers quality butchers','groceries_specialist'),
    ('paperchase','stationery'),
    ('parent pay','school_fees'),
    ('parkdean resorts','holiday_uk'),
    ('parklands country club','private_members_club'),
    ('pay by phone','car_parking'),
    ('paypal','payment_intermediary'),
    ('paypal credit','bnpl'),
    ('pension credit','benefits_state'),
    ('personal independence payment','benefits_state'),
    ('pets at home','pet_supplies'),
    ('pharmacy2u','pharmacy'),
    ('pizza express','restaurant_cafe'),
    ('pizza hut','takeaway'),
    ('planet organic','groceries_specialist'),
    ('play.com','gaming_console_pc'),
    ('playstation','gaming_console_pc'),
    ('plum','savings_transfer'),
    ('pockit','prepaid_card'),
    ('polani travel','travel_other'),
    ('popeyes','takeaway'),
    ('post office','government_services'),
    ('postcode lottery','gambling_lottery'),
    ('poundland','discount_store'),
    ('poundstretcher','discount_store'),
    ('premier man','clothing_mens'),
    ('premier stores','groceries'),
    ('pret a manger','restaurant_cafe'),
    ('pretty little things','clothing_general'),
    ('primark','clothing_general'),
    ('prime','streaming'),
    ('punch bowl','pub_bar'),
    ('pure gym','gym_fitness'),
    ('quiz clothing','clothing_womens'),
    ('rac','breakdown_cover'),
    ('rainbow riches casino','gambling_casino'),
    ('rajapack','office_supplies'),
    ('rangers fc','sports_tickets'),
    ('rated people','tradesmen'),
    ('raylo','retail_finance_repayment'),
    ('reeds rains','estate_agent'),
    ('remitly','transfer_international'),
    ('residential management group','property_management'),
    ('revolucion de cuba','pub_bar'),
    ('revolut','transfer_own_account'),
    ('revolution skatepark','sports_participation'),
    ('ring.com','home_accessories'),
    ('ringgo parking','car_parking'),
    ('river island','clothing_general'),
    ('rocket dog','footwear'),
    ('royal mail','delivery_courier'),
    ('ryanair','flights'),
    ('ryman','stationery'),
    ('sainsbury\'s','groceries'),
    ('sainsbury\'s petrol','fuel'),
    ('saltrock surfwear','clothing_outdoor'),
    ('sandwi on the go ltd','takeaway'),
    ('santander bank','financial_institution_unspecified'),
    ('save the change','savings_transfer'),
    ('save the pennies','savings_transfer'),
    ('savers health','pharmacy'),
    ('school days direct','clothing_childrens'),
    ('school gateway','school_fees'),
    ('school uniform direct','clothing_childrens'),
    ('schoolmoney','school_fees'),
    ('schuh','footwear'),
    ('scotmid co-op','groceries'),
    ('scottish power','energy'),
    ('screwfix','tools'),
    ('scrumbles','pet_supplies'),
    ('secc arena','days_out'),
    ('selecta','confectionary'),
    ('severn trent','water'),
    ('shein','clothing_general'),
    ('shell','fuel'),
    ('skechers','footwear'),
    ('skill on net ltd','gambling_casino'),
    ('skillz esports','gambling_unspecified'),
    ('sky','broadband_tv_phone'),
    ('sky bet','gambling_betting'),
    ('sky mobile','mobile_phone_contract'),
    ('skybet','gambling_betting'),
    ('smarty','mobile_phone_contract'),
    ('smyths toys','toys'),
    ('sony','gaming_console_pc'),
    ('spar','groceries'),
    ('specsavers','optician'),
    ('sports direct','sportswear'),
    ('spotify','streaming'),
    ('st vincent de paul society','charitable_donation'),
    ('stagecoach','public_transport_rail_coach'),
    ('star fish bar','takeaway'),
    ('star pizza','takeaway'),
    ('starbucks','restaurant_cafe'),
    ('starling bank','transfer_own_account'),
    ('state pension','pension_received'),
    ('steamgames','gaming_console_pc'),
    ('stop n shop ltd','convenience_store'),
    ('stripe','payment_intermediary'),
    ('student loans company','student_loan_repayment'),
    ('subway','takeaway'),
    ('sun bingo','gambling_bingo'),
    ('sunlife','insurance_life'),
    ('super pound saver','discount_store'),
    ('supercell','gaming_mobile'),
    ('superdrug','pharmacy'),
    ('taco bell','takeaway'),
    ('tails.com','pet_supplies'),
    ('takeaway.je','takeaway'),
    ('talktalk','broadband_tv_phone'),
    ('taptap send uk limited','transfer_international'),
    ('tariq halal meats','groceries_specialist'),
    ('tasty plaice','takeaway'),
    ('temptation gifts','gifts_flowers'),
    ('terrys fabrics','home_accessories'),
    ('tesco','groceries'),
    ('tesco bank','financial_institution_unspecified'),
    ('tesco fuel','fuel'),
    ('tesco mobile','mobile_phone_contract'),
    ('texaco','fuel'),
    ('tfl','public_transport_rail_coach'),
    ('thai express','takeaway'),
    ('thames water','water'),
    ('that prize guy','prize_competitions'),
    ('the bat and ball','pub_bar'),
    ('the beauty room','beauty_treatment'),
    ('the bedford','pub_bar'),
    ('the bike club','bicycle'),
    ('the bottle shop','alcohol_beer_spirits'),
    ('the cash shop','payday_loan'),
    ('the cricketers','pub_bar'),
    ('the entertainer','toys'),
    ('the gym website','gym_fitness'),
    ('the national lottery','gambling_lottery'),
    ('the north face','clothing_outdoor'),
    ('the orange tree','pub_bar'),
    ('the range','home_accessories'),
    ('the real china','restaurant_cafe'),
    ('the red lion','pub_bar'),
    ('the sheaf island','pub_bar'),
    ('the southern co-op','groceries'),
    ('the tan studio limited','beauty_treatment'),
    ('the tanning rooms','beauty_treatment'),
    ('the volunteer tavern','pub_bar'),
    ('the water margin','restaurant_cafe'),
    ('the white company','home_accessories'),
    ('the works','books'),
    ('the world\'s end','pub_bar'),
    ('thetrainline','public_transport_rail_coach'),
    ('thistle insurance','insurance_general'),
    ('three','mobile_phone_contract'),
    ('tian tian market','groceries_specialist'),
    ('tick tock loans','payday_loan'),
    ('tiktok','online_services'),
    ('tiso','clothing_outdoor'),
    ('tk maxx','clothing_general'),
    ('toffs','sportswear'),
    ('tombola','gambling_bingo'),
    ('toolstation','tools'),
    ('top wok','takeaway'),
    ('topshop','clothing_womens'),
    ('traid','charity_shop'),
    ('transport for london','public_transport_rail_coach'),
    ('treatwell','beauty_treatment'),
    ('trip.com','accommodation'),
    ('triple s caterers','catering'),
    ('trustly group','payment_intermediary'),
    ('tsb','financial_institution_unspecified'),
    ('tv licensing','tv_licence'),
    ('u.s. post office','delivery_courier'),
    ('uber','taxi_rideshare'),
    ('uber eats','takeaway'),
    ('ugg australia','footwear'),
    ('uk usa eliquids ltd','vaping'),
    ('ultrasound direct','health_other'),
    ('unibet','gambling_betting'),
    ('united utilities','water'),
    ('universal credit','benefits_state'),
    ('uphold','crypto'),
    ('utilita','energy'),
    ('v kent minimart ltd','convenience_store'),
    ('v12 retail finance','retail_finance_repayment'),
    ('vanquis bank','credit_card_repayment'),
    ('very','catalogue_retail'),
    ('vets gen','veterinary'),
    ('vetsure','insurance_pet'),
    ('vinted','marketplace_general'),
    ('virgin bet','gambling_betting'),
    ('virgin games','gambling_casino'),
    ('virgin media','broadband_tv_phone'),
    ('vistaprint','printing_services'),
    ('vodafone','mobile_phone_contract'),
    ('voxi','mobile_phone_contract'),
    ('vue cinemas','cinema'),
    ('w.h.smith','books'),
    ('waitrose','groceries'),
    ('walkabout','pub_bar'),
    ('wawel polski sklep','groceries_specialist'),
    ('welcome break','convenience_store'),
    ('wetherspoon','pub_bar'),
    ('wickes','home_improvement'),
    ('wiggleys fun farm ltd','days_out'),
    ('wilko.com','home_accessories'),
    ('william hill','gambling_betting'),
    ('workwear express','clothing_workwear'),
    ('wynsors','footwear'),
    ('xbox','gaming_console_pc'),
    ('yew tree mini market','convenience_store'),
    ('youtube premium','streaming'),
    ('zable credit card','credit_card_repayment'),
    ('zara','clothing_general'),
    ('zenfolio','photography_services'),
    ('zilch','bnpl'),
    ('zopa','personal_loan_repayment')
])),
leaf_meta AS (SELECT * FROM UNNEST([STRUCT<leaf STRING, general_category STRING, necessity STRING,
  cash_flow_type STRING, is_debt_related BOOL, is_priority_debt BOOL, is_age_restricted BOOL, risk_flag STRING>
    ('accommodation','travel_holidays','discretionary','spend',false,false,false,'none'),
    ('account_charge','fees_charges','not_applicable','fee_or_penalty',false,false,false,'none'),
    ('account_misuse','high_cost_distress_credit','not_applicable','fee_or_penalty',false,false,false,'distress_signal'),
    ('accountancy','business_self_employment','mixed_basket','spend',false,false,false,'none'),
    ('adjustment','unclassified','mixed_basket','spend',false,false,false,'none'),
    ('adult_care','health_medical','essential','spend',false,false,false,'none'),
    ('adult_entertainment','entertainment_leisure','discretionary','spend',false,false,true,'none'),
    ('adult_products','entertainment_leisure','discretionary','spend',false,false,true,'none'),
    ('advertising_services','business_self_employment','mixed_basket','spend',false,false,false,'none'),
    ('airport_parking','travel_holidays','discretionary','spend',false,false,false,'none'),
    ('airport_spend','travel_holidays','discretionary','spend',false,false,false,'none'),
    ('alcohol_beer_spirits','groceries_household_essentials','discretionary','spend',false,false,true,'none'),
    ('alcohol_wine','groceries_household_essentials','discretionary','spend',false,false,true,'none'),
    ('arts_crafts','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('audio_equipment','general_retail_marketplaces','discretionary','spend',false,false,false,'none'),
    ('baby_products','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('balance_transfer','credit_loan_repayments','essential','debt_repayment',true,false,false,'none'),
    ('balance_transfer_fee','fees_charges','not_applicable','fee_or_penalty',true,false,false,'none'),
    ('bank_charge_other','fees_charges','not_applicable','fee_or_penalty',false,false,false,'none'),
    ('bathroom','home_garden','mixed_basket','spend',false,false,false,'none'),
    ('beauty_treatment','clothing_personal_care','discretionary','spend',false,false,false,'none'),
    ('bedding','home_garden','mixed_basket','spend',false,false,false,'none'),
    ('benefits_state','income_benefits_state_support','not_applicable','income',false,false,false,'none'),
    ('bicycle','transport_motoring','mixed_basket','spend',false,false,false,'none'),
    ('bnpl','credit_loan_repayments','essential','debt_repayment',true,false,false,'high_cost_credit'),
    ('books','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('breakdown_cover','transport_motoring','essential','spend',false,false,false,'none'),
    ('broadband_tv_phone','utilities_household_bills','essential','spend',false,false,false,'none'),
    ('business_loan_repayment','business_self_employment','essential','debt_repayment',true,false,false,'none'),
    ('business_services','business_self_employment','mixed_basket','spend',false,false,false,'none'),
    ('camera_photography','general_retail_marketplaces','discretionary','spend',false,false,false,'none'),
    ('camping_equipment','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('camping_holiday','travel_holidays','discretionary','spend',false,false,false,'none'),
    ('car_finance_repayment','credit_loan_repayments','essential','debt_repayment',true,false,false,'none'),
    ('car_hire','transport_motoring','discretionary','spend',false,false,false,'none'),
    ('car_lease','credit_loan_repayments','essential','debt_repayment',true,false,false,'none'),
    ('car_parking','transport_motoring','essential','spend',false,false,false,'none'),
    ('card_payment_unspecified','transfers','not_applicable','transfer_own_accounts',false,false,false,'none'),
    ('career_services','childcare_education','discretionary','spend',false,false,false,'none'),
    ('carwash','transport_motoring','discretionary','spend',false,false,false,'none'),
    ('cash_advance','high_cost_distress_credit','essential','debt_repayment',true,false,false,'high_cost_credit'),
    ('cash_advance_fee','high_cost_distress_credit','not_applicable','fee_or_penalty',false,false,false,'distress_fee'),
    ('cash_and_carry','groceries_household_essentials','essential','spend',false,false,false,'none'),
    ('cash_deposit','cash','not_applicable','transfer_own_accounts',false,false,false,'visibility_loss'),
    ('cash_withdrawal','cash','not_applicable','transfer_own_accounts',false,false,false,'visibility_loss'),
    ('cashback','income_other','not_applicable','income',false,false,false,'none'),
    ('catalogue_retail','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('catering','eating_drinking_out','discretionary','spend',false,false,false,'none'),
    ('charge_card_repayment','credit_loan_repayments','essential','debt_repayment',true,false,false,'none'),
    ('charitable_donation','charitable_political_giving','discretionary','spend',false,false,false,'none'),
    ('charity_shop','charitable_political_giving','discretionary','spend',false,false,false,'none'),
    ('cheque','transfers','not_applicable','transfer_own_accounts',false,false,false,'none'),
    ('childcare','childcare_education','essential','spend',false,false,false,'none'),
    ('cinema','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('cleaning_services','home_garden','discretionary','spend',false,false,false,'none'),
    ('clothing_childrens','clothing_personal_care','mixed_basket','spend',false,false,false,'none'),
    ('clothing_general','clothing_personal_care','mixed_basket','spend',false,false,false,'none'),
    ('clothing_maternity','clothing_personal_care','mixed_basket','spend',false,false,false,'none'),
    ('clothing_mens','clothing_personal_care','mixed_basket','spend',false,false,false,'none'),
    ('clothing_outdoor','clothing_personal_care','discretionary','spend',false,false,false,'none'),
    ('clothing_womens','clothing_personal_care','mixed_basket','spend',false,false,false,'none'),
    ('clothing_workwear','clothing_personal_care','essential','spend',false,false,false,'none'),
    ('comics','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('computer_peripherals','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('computing_devices','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('confectionary','groceries_household_essentials','discretionary','spend',false,false,false,'none'),
    ('construction_services','home_garden','mixed_basket','spend',false,false,false,'none'),
    ('convenience_store','groceries_household_essentials','mixed_basket','spend',false,false,false,'none'),
    ('council_tax','council_tax_government','essential','spend',false,true,false,'none'),
    ('credit_card_fee','fees_charges','not_applicable','fee_or_penalty',true,false,false,'none'),
    ('credit_card_repayment','credit_loan_repayments','essential','debt_repayment',true,false,false,'none'),
    ('credit_reporting_service','high_cost_distress_credit','discretionary','spend',false,false,false,'distress_signal'),
    ('credit_union_repayment','credit_loan_repayments','essential','debt_repayment',true,false,false,'none'),
    ('crypto','savings_investments','not_applicable','transfer_own_accounts',false,false,false,'speculative_asset'),
    ('days_out','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('debt_collection','high_cost_distress_credit','essential','debt_repayment',true,false,false,'distress_signal'),
    ('debt_enforcement','high_cost_distress_credit','essential','debt_repayment',true,false,false,'distress_signal'),
    ('debt_management_plan','high_cost_distress_credit','essential','debt_repayment',true,false,false,'distress_signal'),
    ('delivery_courier','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('dentist','health_medical','essential','spend',false,false,false,'none'),
    ('department_store','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('discount_store','groceries_household_essentials','essential','spend',false,false,false,'none'),
    ('dividend_received','income_other','not_applicable','income',false,false,false,'none'),
    ('driving_tuition','childcare_education','discretionary','spend',false,false,false,'none'),
    ('eating_out_other','eating_drinking_out','discretionary','spend',false,false,false,'none'),
    ('education_general','childcare_education','essential','spend',false,false,false,'none'),
    ('electrical_goods','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('email_services','digital_subscriptions_services','discretionary','spend',false,false,false,'none'),
    ('emergency_services','council_tax_government','essential','spend',false,false,false,'none'),
    ('employee_benefits','income_employment','not_applicable','income',false,false,false,'none'),
    ('energy','utilities_household_bills','essential','spend',false,true,false,'none'),
    ('entertainment_other','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('estate_agent','housing','mixed_basket','spend',false,false,false,'none'),
    ('event_planning','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('experience_days','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('family_services','health_medical','essential','spend',false,false,false,'none'),
    ('fancy_dress','clothing_personal_care','discretionary','spend',false,false,false,'none'),
    ('ferry_rail_travel','travel_holidays','discretionary','spend',false,false,false,'none'),
    ('financial_institution_unspecified','unclassified','mixed_basket','spend',false,false,false,'none'),
    ('financial_services_other','credit_loan_repayments','mixed_basket','spend',false,false,false,'none'),
    ('flights','travel_holidays','discretionary','spend',false,false,false,'none'),
    ('footwear','clothing_personal_care','mixed_basket','spend',false,false,false,'none'),
    ('foreign_currency','travel_holidays','discretionary','spend',false,false,false,'none'),
    ('foreign_spend_unspecified','travel_holidays','mixed_basket','spend',false,false,false,'none'),
    ('forex_trading','savings_investments','not_applicable','transfer_own_accounts',false,false,false,'speculative_asset'),
    ('fragrances','clothing_personal_care','discretionary','spend',false,false,false,'none'),
    ('fuel','transport_motoring','essential','spend',false,false,false,'none'),
    ('funeral','health_medical','essential','spend',false,false,false,'none'),
    ('gadgets','general_retail_marketplaces','discretionary','spend',false,false,false,'none'),
    ('gambling_betting','gambling','discretionary','spend',false,false,true,'behavioural_risk'),
    ('gambling_bingo','gambling','discretionary','spend',false,false,true,'behavioural_risk'),
    ('gambling_casino','gambling','discretionary','spend',false,false,true,'behavioural_risk'),
    ('gambling_lottery','gambling','discretionary','spend',false,false,true,'low_stakes_gambling'),
    ('gambling_unspecified','gambling','discretionary','spend',false,false,true,'behavioural_risk'),
    ('games_puzzles','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('gaming_console_pc','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('gaming_mobile','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('gaming_online','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('garden','home_garden','discretionary','spend',false,false,false,'none'),
    ('genealogy_services','digital_subscriptions_services','discretionary','spend',false,false,false,'none'),
    ('gifts_flowers','general_retail_marketplaces','discretionary','spend',false,false,false,'none'),
    ('government_services','council_tax_government','essential','spend',false,false,false,'none'),
    ('groceries','groceries_household_essentials','essential','spend',false,false,false,'none'),
    ('groceries_specialist','groceries_household_essentials','essential','spend',false,false,false,'none'),
    ('gym_fitness','health_medical','discretionary','spend',false,false,false,'none'),
    ('health_beauty_general','clothing_personal_care','discretionary','spend',false,false,false,'none'),
    ('health_other','health_medical','essential','spend',false,false,false,'none'),
    ('heating_oil','utilities_household_bills','essential','spend',false,true,false,'none'),
    ('hire_purchase_repayment','credit_loan_repayments','essential','debt_repayment',true,false,false,'none'),
    ('holiday_package','travel_holidays','discretionary','spend',false,false,false,'none'),
    ('holiday_rental','travel_holidays','discretionary','spend',false,false,false,'none'),
    ('holiday_uk','travel_holidays','discretionary','spend',false,false,false,'none'),
    ('home_accessories','home_garden','mixed_basket','spend',false,false,false,'none'),
    ('home_improvement','home_garden','mixed_basket','spend',false,false,false,'none'),
    ('home_learning','childcare_education','essential','spend',false,false,false,'none'),
    ('home_repair','home_garden','essential','spend',false,false,false,'none'),
    ('hospital','health_medical','essential','spend',false,false,false,'none'),
    ('household_appliances','home_garden','mixed_basket','spend',false,false,false,'none'),
    ('housing_benefit','income_benefits_state_support','not_applicable','income',false,false,false,'none'),
    ('housing_other','housing','essential','spend',false,false,false,'none'),
    ('id_documents','council_tax_government','essential','spend',false,false,false,'none'),
    ('income_agency_work','income_employment','not_applicable','income',false,false,false,'none'),
    ('income_other_unspecified','income_other','not_applicable','income',false,false,false,'none'),
    ('insurance_general','insurance','essential','spend',false,false,false,'none'),
    ('insurance_health','insurance','essential','spend',false,false,false,'none'),
    ('insurance_home','insurance','essential','spend',false,false,false,'none'),
    ('insurance_life','insurance','essential','spend',false,false,false,'none'),
    ('insurance_motor','insurance','essential','spend',false,false,false,'none'),
    ('insurance_other','insurance','essential','spend',false,false,false,'none'),
    ('insurance_pet','pets','discretionary','spend',false,false,false,'none'),
    ('insurance_travel','insurance','discretionary','spend',false,false,false,'none'),
    ('interest_charged','fees_charges','not_applicable','fee_or_penalty',true,false,false,'none'),
    ('investment_general','savings_investments','not_applicable','transfer_own_accounts',false,false,false,'none'),
    ('investment_trading','savings_investments','not_applicable','transfer_own_accounts',false,false,false,'none'),
    ('it_services','business_self_employment','mixed_basket','spend',false,false,false,'none'),
    ('jewellery','clothing_personal_care','discretionary','spend',false,false,false,'none'),
    ('kitchen','home_garden','mixed_basket','spend',false,false,false,'none'),
    ('laundry','home_garden','essential','spend',false,false,false,'none'),
    ('legal_services','business_self_employment','mixed_basket','spend',false,false,false,'none'),
    ('lighting','home_garden','mixed_basket','spend',false,false,false,'none'),
    ('live_music','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('loan_disbursement','credit_loan_repayments','not_applicable','debt_disbursement',true,false,false,'none'),
    ('loan_repayment_dd','credit_loan_repayments','essential','debt_repayment',true,false,false,'none'),
    ('loan_repayment_manual','credit_loan_repayments','essential','debt_repayment',true,false,false,'none'),
    ('loan_repayment_other','credit_loan_repayments','essential','debt_repayment',true,false,false,'none'),
    ('luggage_travel_goods','travel_holidays','discretionary','spend',false,false,false,'none'),
    ('magazines','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('marketplace_amazon','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('marketplace_general','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('marketplace_refurbished','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('medicine','health_medical','essential','spend',false,false,false,'none'),
    ('memberships','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('mental_health_services','health_medical','essential','spend',false,false,false,'none'),
    ('mobile_handset','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('mobile_phone_contract','utilities_household_bills','essential','spend',false,false,false,'none'),
    ('money_management_service','high_cost_distress_credit','discretionary','spend',false,false,false,'distress_signal'),
    ('money_transfer_fee','fees_charges','not_applicable','fee_or_penalty',false,false,false,'none'),
    ('money_transfer_service','transfers','not_applicable','p2p_transfer',false,false,false,'none'),
    ('mortgage','housing','essential','debt_repayment',true,true,false,'none'),
    ('music_other','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('musical_instruments','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('newspapers','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('night_club','eating_drinking_out','discretionary','spend',false,false,true,'none'),
    ('office_equipment','business_self_employment','mixed_basket','spend',false,false,false,'none'),
    ('office_supplies','business_self_employment','mixed_basket','spend',false,false,false,'none'),
    ('online_dating','digital_subscriptions_services','discretionary','spend',false,false,true,'none'),
    ('online_services','digital_subscriptions_services','discretionary','spend',false,false,false,'none'),
    ('optician','health_medical','essential','spend',false,false,false,'none'),
    ('overdraft_arranged','fees_charges','not_applicable','fee_or_penalty',true,false,false,'none'),
    ('overdraft_unarranged','high_cost_distress_credit','not_applicable','fee_or_penalty',false,false,false,'distress_fee'),
    ('pawnbroker','high_cost_distress_credit','essential','debt_repayment',true,false,false,'high_cost_credit'),
    ('payday_loan','high_cost_distress_credit','essential','debt_repayment',true,false,false,'high_cost_credit'),
    ('payment_intermediary','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('pension_contribution','savings_investments','not_applicable','transfer_own_accounts',false,false,false,'none'),
    ('pension_received','income_other','not_applicable','income',false,false,false,'none'),
    ('personal_loan_repayment','credit_loan_repayments','essential','debt_repayment',true,false,false,'none'),
    ('pet_other','pets','discretionary','spend',false,false,false,'none'),
    ('pet_supplies','pets','discretionary','spend',false,false,false,'none'),
    ('pharmacy','health_medical','essential','spend',false,false,false,'none'),
    ('photography_services','business_self_employment','mixed_basket','spend',false,false,false,'none'),
    ('physical_media','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('political_donation','charitable_political_giving','discretionary','spend',false,false,false,'none'),
    ('prepaid_card','transfers','not_applicable','transfer_own_accounts',false,false,false,'none'),
    ('printing_services','business_self_employment','mixed_basket','spend',false,false,false,'none'),
    ('printing_supplies','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('private_members_club','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('prize_competitions','gambling','discretionary','spend',false,false,true,'low_stakes_gambling'),
    ('property_management','housing','essential','spend',false,true,false,'none'),
    ('pub_bar','eating_drinking_out','discretionary','spend',false,false,true,'none'),
    ('public_transport_rail_coach','transport_motoring','essential','spend',false,false,false,'none'),
    ('refund_received','income_other','not_applicable','income',false,false,false,'none'),
    ('rent','housing','essential','spend',false,true,false,'none'),
    ('restaurant_cafe','eating_drinking_out','discretionary','spend',false,false,false,'none'),
    ('retail_finance_repayment','credit_loan_repayments','essential','debt_repayment',true,false,false,'none'),
    ('retail_other','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('retail_small_independent','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('retail_tv_online_shopping','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('returned_payment','fees_charges','not_applicable','fee_or_penalty',false,false,false,'distress_fee'),
    ('revolving_credit_repayment','credit_loan_repayments','essential','debt_repayment',true,false,false,'none'),
    ('road_tax','transport_motoring','essential','spend',false,false,false,'none'),
    ('salary','income_employment','not_applicable','income',false,false,false,'none'),
    ('salary_gig','income_employment','not_applicable','income',false,false,false,'none'),
    ('savings_interest_received','income_other','not_applicable','income',false,false,false,'none'),
    ('savings_transfer','savings_investments','not_applicable','transfer_own_accounts',false,false,false,'none'),
    ('school_fees','childcare_education','essential','spend',false,false,false,'none'),
    ('services_unspecified','unclassified','mixed_basket','spend',false,false,false,'none'),
    ('skin_hair_care','clothing_personal_care','discretionary','spend',false,false,false,'none'),
    ('social_reporting','digital_subscriptions_services','discretionary','spend',false,false,false,'none'),
    ('software','digital_subscriptions_services','discretionary','spend',false,false,false,'none'),
    ('spares_repairs','transport_motoring','essential','spend',false,false,false,'none'),
    ('sports_equipment','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('sports_participation','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('sports_tickets','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('sportswear','clothing_personal_care','discretionary','spend',false,false,false,'none'),
    ('stationery','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('storage','housing','discretionary','spend',false,false,false,'none'),
    ('streaming','digital_subscriptions_services','discretionary','spend',false,false,false,'none'),
    ('student_loan_repayment','credit_loan_repayments','essential','debt_repayment',true,false,false,'none'),
    ('supplements','health_medical','discretionary','spend',false,false,false,'none'),
    ('takeaway','eating_drinking_out','discretionary','spend',false,false,false,'none'),
    ('tax_payment','council_tax_government','essential','spend',false,true,false,'none'),
    ('tax_refund','income_other','not_applicable','income',false,false,false,'none'),
    ('taxi_rideshare','transport_motoring','mixed_basket','spend',false,false,false,'none'),
    ('theatre','entertainment_leisure','discretionary','spend',false,false,false,'none'),
    ('tobacco','groceries_household_essentials','discretionary','spend',false,false,true,'none'),
    ('tolls','transport_motoring','essential','spend',false,false,false,'none'),
    ('tools','home_garden','mixed_basket','spend',false,false,false,'none'),
    ('toys','general_retail_marketplaces','discretionary','spend',false,false,false,'none'),
    ('trade_union','business_self_employment','mixed_basket','spend',false,false,false,'none'),
    ('tradesmen','home_garden','essential','spend',false,false,false,'none'),
    ('transfer_bank_unspecified','transfers','not_applicable','transfer_own_accounts',false,false,false,'none'),
    ('transfer_international','transfers','not_applicable','p2p_transfer',false,false,false,'none'),
    ('transfer_mobile_app','transfers','not_applicable','p2p_transfer',false,false,false,'none'),
    ('transfer_own_account','transfers','not_applicable','transfer_own_accounts',false,false,false,'none'),
    ('transfer_p2p','transfers','not_applicable','p2p_transfer',false,false,false,'none'),
    ('transport_other','transport_motoring','essential','spend',false,false,false,'none'),
    ('travel_other','travel_holidays','discretionary','spend',false,false,false,'none'),
    ('tv_licence','utilities_household_bills','essential','spend',false,true,false,'none'),
    ('unclassified_card_spend','unclassified','mixed_basket','spend',false,false,false,'none'),
    ('unclassified_other','unclassified','mixed_basket','spend',false,false,false,'none'),
    ('unclassified_recurring','unclassified','mixed_basket','spend',false,false,false,'none'),
    ('unclassified_transfer','unclassified','mixed_basket','spend',false,false,false,'none'),
    ('utility_other','utilities_household_bills','essential','spend',false,true,false,'none'),
    ('vaping','groceries_household_essentials','discretionary','spend',false,false,true,'none'),
    ('vehicle_maintenance','transport_motoring','essential','spend',false,false,false,'none'),
    ('vehicle_mot','transport_motoring','essential','spend',false,false,false,'none'),
    ('vehicle_purchase','transport_motoring','mixed_basket','spend',false,false,false,'none'),
    ('vehicle_servicing','transport_motoring','essential','spend',false,false,false,'none'),
    ('veterinary','pets','essential','spend',false,false,false,'none'),
    ('vouchers','general_retail_marketplaces','mixed_basket','spend',false,false,false,'none'),
    ('waste_services','utilities_household_bills','essential','spend',false,false,false,'none'),
    ('water','utilities_household_bills','essential','spend',false,true,false,'none'),
    ('wealth_management','savings_investments','not_applicable','transfer_own_accounts',false,false,false,'none'),
    ('web_services','digital_subscriptions_services','discretionary','spend',false,false,false,'none'),
    ('weight_loss','health_medical','discretionary','spend',false,false,false,'none')
])),

-- ---------- EQUIFAX ----------
eqx_raw AS (
  SELECT
    PrimaryCategoryDescription AS pri,
    SubCategoryDescription AS sub,
    VendorDescription AS vendor,
    Description AS description_raw,
    IF(TransactionTypeId=1,'credit','debit') AS direction,
    Amount
  FROM `raylo-production.equifax_data.open_banking_full_dump`
  TABLESAMPLE SYSTEM (2 PERCENT)
),
eqx_resolved AS (
  SELECT r.*,
    CASE
      -- T1: direction-dependent overrides
      WHEN r.pri LIKE 'Gambling and Betting%' AND r.direction='credit' THEN 'gambling_unspecified'
      WHEN r.sub='Council' AND r.direction='credit' THEN 'salary'
      -- T2: compound rule - gig income
      WHEN r.pri='Identified Salary' AND r.sub IN ('Taxis','Delivery','Take Away') THEN 'salary_gig'
      WHEN r.pri='Identified Salary' AND r.sub IN ('Recruitment Services','Employment Agencies') THEN 'income_agency_work'
      -- T3: MECHANISM-OVERRIDE primaries (mechanism determines leaf regardless of merchant)
      WHEN r.pri='Identified Salary' THEN 'salary'
      WHEN r.pri='Refund' THEN 'refund_received'
      WHEN r.pri IN ('Benefits','Welfare') THEN 'benefits_state'
      WHEN r.pri='Pension Payout' THEN 'pension_received'
      WHEN r.pri='Tax Refund' THEN 'tax_refund'
      WHEN r.pri='Cash Back' THEN 'cashback'
      WHEN r.pri='Cash Machine' THEN 'cash_withdrawal'
      WHEN r.pri='Cash Deposit' THEN 'cash_deposit'
      WHEN r.pri IN ('Interest','Interests and Dividends') THEN 'savings_interest_received'
      WHEN r.pri='Balance Transfers' THEN 'balance_transfer'
      WHEN r.pri='Adjustments' THEN 'adjustment'
      -- T4: merchant dictionary (provider-independent, overrides both providers' own categories)
      WHEN d.leaf IS NOT NULL THEN d.leaf
      -- T5: deterministic rules
      WHEN REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '^(mr|mrs|miss|ms|dr)\\s+') THEN 'transfer_p2p'
      WHEN REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '^[a-z]\\s+[a-z]{2,}$') THEN 'transfer_p2p'
      WHEN REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), CONCAT(r'\b(', 'mum|dad|mom|nan|nana|gran|granny|grandad|sister|brother|son|daughter|wife|husband', r')\b')) THEN 'transfer_p2p'
      WHEN REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '^exchanged to (btc|eth|sol|xrp|ada|doge)') THEN 'crypto'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '(petrol|fuel)\\s*(station)?$') AND r.direction = 'debit') THEN 'fuel'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '(bingo|casino)') AND r.direction = 'debit') THEN 'gambling_unspecified'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '\\b(bet|betting|bookmaker)\\b') AND r.direction = 'debit') THEN 'gambling_betting'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '\\b(lottery|lotto)\\b') AND r.direction = 'debit') THEN 'gambling_lottery'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '\\b(debt (collection|recovery)|collections? ltd)\\b') AND r.direction = 'debit') THEN 'debt_collection'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), CONCAT(r'\b(', 'child maintenance', r')\b')) AND r.direction = 'credit') THEN 'income_other_unspecified'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), CONCAT(r'\b(', 'we buy any car', r')\b')) AND r.direction = 'credit') THEN 'income_other_unspecified'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), CONCAT(r'\b(', 'we buy any car', r')\b')) AND r.direction = 'debit') THEN 'vehicle_purchase'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '\\b(car park|parking)\\b') AND r.direction = 'debit') THEN 'car_parking'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '\\b(vets?|veterinary)\\b') AND r.direction = 'debit') THEN 'veterinary'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '\\b(pharmacy|chemist)\\b') AND r.direction = 'debit') THEN 'pharmacy'
      WHEN (REGEXP_CONTAINS(LOWER(COALESCE(r.description_raw, '')), '\\bcouncil tax\\b') AND r.direction = 'debit') THEN 'council_tax'
      -- T6: provider crosswalk fallback (sub = WHAT, primary = mechanism fallback)
      WHEN s.leaf IS NOT NULL THEN s.leaf
      WHEN p.leaf IS NOT NULL THEN p.leaf
      ELSE 'unclassified_other'
    END AS leaf,
    CASE
      WHEN r.pri LIKE 'Gambling and Betting%' AND r.direction='credit' THEN 'T1_direction'
      WHEN r.sub='Council' AND r.direction='credit' THEN 'T1_direction'
      WHEN r.pri='Identified Salary' AND r.sub IN ('Taxis','Delivery','Take Away') THEN 'T2_compound'
      WHEN r.pri='Identified Salary' AND r.sub IN ('Recruitment Services','Employment Agencies') THEN 'T2_compound'
      WHEN r.pri IN ('Identified Salary','Refund','Benefits','Welfare','Pension Payout','Tax Refund',
        'Cash Back','Cash Machine','Cash Deposit','Interest','Interests and Dividends',
        'Balance Transfers','Adjustments') THEN 'T3_mechanism_override'
      WHEN d.leaf IS NOT NULL THEN 'T4_merchant_dictionary'
      WHEN REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '^(mr|mrs|miss|ms|dr)\\s+') THEN 'T5_rule_R01'
      WHEN REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '^[a-z]\\s+[a-z]{2,}$') THEN 'T5_rule_R02'
      WHEN REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), CONCAT(r'\b(', 'mum|dad|mom|nan|nana|gran|granny|grandad|sister|brother|son|daughter|wife|husband', r')\b')) THEN 'T5_rule_R03'
      WHEN REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '^exchanged to (btc|eth|sol|xrp|ada|doge)') THEN 'T5_rule_R04'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '(petrol|fuel)\\s*(station)?$') AND r.direction = 'debit') THEN 'T5_rule_R05'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '(bingo|casino)') AND r.direction = 'debit') THEN 'T5_rule_R06'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '\\b(bet|betting|bookmaker)\\b') AND r.direction = 'debit') THEN 'T5_rule_R07'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '\\b(lottery|lotto)\\b') AND r.direction = 'debit') THEN 'T5_rule_R08'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '\\b(debt (collection|recovery)|collections? ltd)\\b') AND r.direction = 'debit') THEN 'T5_rule_R14'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), CONCAT(r'\b(', 'child maintenance', r')\b')) AND r.direction = 'credit') THEN 'T5_rule_R15'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), CONCAT(r'\b(', 'we buy any car', r')\b')) AND r.direction = 'credit') THEN 'T5_rule_R16'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), CONCAT(r'\b(', 'we buy any car', r')\b')) AND r.direction = 'debit') THEN 'T5_rule_R17'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '\\b(car park|parking)\\b') AND r.direction = 'debit') THEN 'T5_rule_R09'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '\\b(vets?|veterinary)\\b') AND r.direction = 'debit') THEN 'T5_rule_R10'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.vendor)), '\\b(pharmacy|chemist)\\b') AND r.direction = 'debit') THEN 'T5_rule_R11'
      WHEN (REGEXP_CONTAINS(LOWER(COALESCE(r.description_raw, '')), '\\bcouncil tax\\b') AND r.direction = 'debit') THEN 'T5_rule_R12'
      WHEN s.leaf IS NOT NULL THEN 'T6_provider_crosswalk'
      WHEN p.leaf IS NOT NULL THEN 'T6_provider_crosswalk'
      ELSE 'T7_unclassified'
    END AS resolution_tier
  FROM eqx_raw r
  LEFT JOIN sub_xw s ON r.sub = s.eqx_sub
  LEFT JOIN pri_xw p ON r.pri = p.eqx_pri
  LEFT JOIN dict_xw d ON LOWER(TRIM(r.vendor)) = d.merchant
),

-- ---------- PLAID ----------
plaid_raw AS (
  SELECT credit_category_detailed AS cat,
         merchant_name AS merchant_raw,
         COALESCE(original_description, transaction_name) AS description_raw,
         IF(amount < 0,'credit','debit') AS direction, amount AS Amount
  FROM `raylo-production.dbt_production.credit_plaid_open_banking_transactions`
  TABLESAMPLE SYSTEM (20 PERCENT)
),
plaid_resolved AS (
  SELECT r.*,
    CASE
      -- T1: direction-dependent overrides
      WHEN r.cat='ENTERTAINMENT_CASINOS_AND_GAMBLING' AND r.direction='credit' THEN 'gambling_unspecified'
      -- T4: merchant dictionary (provider-independent, overrides both providers' own categories)
      WHEN d.leaf IS NOT NULL THEN d.leaf
      -- T5: deterministic rules
      WHEN REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '^(mr|mrs|miss|ms|dr)\\s+') THEN 'transfer_p2p'
      WHEN REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '^[a-z]\\s+[a-z]{2,}$') THEN 'transfer_p2p'
      WHEN REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), CONCAT(r'\b(', 'mum|dad|mom|nan|nana|gran|granny|grandad|sister|brother|son|daughter|wife|husband', r')\b')) THEN 'transfer_p2p'
      WHEN REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '^exchanged to (btc|eth|sol|xrp|ada|doge)') THEN 'crypto'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '(petrol|fuel)\\s*(station)?$') AND r.direction = 'debit') THEN 'fuel'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '(bingo|casino)') AND r.direction = 'debit') THEN 'gambling_unspecified'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '\\b(bet|betting|bookmaker)\\b') AND r.direction = 'debit') THEN 'gambling_betting'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '\\b(lottery|lotto)\\b') AND r.direction = 'debit') THEN 'gambling_lottery'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '\\b(debt (collection|recovery)|collections? ltd)\\b') AND r.direction = 'debit') THEN 'debt_collection'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), CONCAT(r'\b(', 'child maintenance', r')\b')) AND r.direction = 'credit') THEN 'income_other_unspecified'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), CONCAT(r'\b(', 'we buy any car', r')\b')) AND r.direction = 'credit') THEN 'income_other_unspecified'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), CONCAT(r'\b(', 'we buy any car', r')\b')) AND r.direction = 'debit') THEN 'vehicle_purchase'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '\\b(car park|parking)\\b') AND r.direction = 'debit') THEN 'car_parking'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '\\b(vets?|veterinary)\\b') AND r.direction = 'debit') THEN 'veterinary'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '\\b(pharmacy|chemist)\\b') AND r.direction = 'debit') THEN 'pharmacy'
      WHEN (REGEXP_CONTAINS(LOWER(COALESCE(r.description_raw, '')), '\\bcouncil tax\\b') AND r.direction = 'debit') THEN 'council_tax'
      -- T6: provider crosswalk fallback
      WHEN x.leaf IS NOT NULL THEN x.leaf
      ELSE 'unclassified_other'
    END AS leaf,
    CASE
      WHEN r.cat='ENTERTAINMENT_CASINOS_AND_GAMBLING' AND r.direction='credit' THEN 'T1_direction'
      WHEN d.leaf IS NOT NULL THEN 'T4_merchant_dictionary'
      WHEN REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '^(mr|mrs|miss|ms|dr)\\s+') THEN 'T5_rule_R01'
      WHEN REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '^[a-z]\\s+[a-z]{2,}$') THEN 'T5_rule_R02'
      WHEN REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), CONCAT(r'\b(', 'mum|dad|mom|nan|nana|gran|granny|grandad|sister|brother|son|daughter|wife|husband', r')\b')) THEN 'T5_rule_R03'
      WHEN REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '^exchanged to (btc|eth|sol|xrp|ada|doge)') THEN 'T5_rule_R04'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '(petrol|fuel)\\s*(station)?$') AND r.direction = 'debit') THEN 'T5_rule_R05'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '(bingo|casino)') AND r.direction = 'debit') THEN 'T5_rule_R06'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '\\b(bet|betting|bookmaker)\\b') AND r.direction = 'debit') THEN 'T5_rule_R07'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '\\b(lottery|lotto)\\b') AND r.direction = 'debit') THEN 'T5_rule_R08'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '\\b(debt (collection|recovery)|collections? ltd)\\b') AND r.direction = 'debit') THEN 'T5_rule_R14'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), CONCAT(r'\b(', 'child maintenance', r')\b')) AND r.direction = 'credit') THEN 'T5_rule_R15'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), CONCAT(r'\b(', 'we buy any car', r')\b')) AND r.direction = 'credit') THEN 'T5_rule_R16'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), CONCAT(r'\b(', 'we buy any car', r')\b')) AND r.direction = 'debit') THEN 'T5_rule_R17'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '\\b(car park|parking)\\b') AND r.direction = 'debit') THEN 'T5_rule_R09'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '\\b(vets?|veterinary)\\b') AND r.direction = 'debit') THEN 'T5_rule_R10'
      WHEN (REGEXP_CONTAINS(LOWER(TRIM(r.merchant_raw)), '\\b(pharmacy|chemist)\\b') AND r.direction = 'debit') THEN 'T5_rule_R11'
      WHEN (REGEXP_CONTAINS(LOWER(COALESCE(r.description_raw, '')), '\\bcouncil tax\\b') AND r.direction = 'debit') THEN 'T5_rule_R12'
      WHEN x.leaf IS NOT NULL THEN 'T6_provider_crosswalk'
      ELSE 'T7_unclassified'
    END AS resolution_tier
  FROM plaid_raw r
  LEFT JOIN plaid_xw x ON r.cat = x.plaid_cat
  LEFT JOIN dict_xw d ON LOWER(TRIM(r.merchant_raw)) = d.merchant
),

combined AS (
  SELECT 'equifax' AS provider, leaf, resolution_tier FROM eqx_resolved
  UNION ALL
  SELECT 'plaid', leaf, resolution_tier FROM plaid_resolved
)
SELECT
  c.provider, c.resolution_tier,
  COUNT(*) AS n,
  ROUND(100*COUNT(*)/SUM(COUNT(*)) OVER (PARTITION BY c.provider),2) AS pct_of_provider,
  COUNT(DISTINCT c.leaf) AS distinct_leaves,
  COUNTIF(m.leaf IS NULL) AS leaves_missing_metadata
FROM combined c
LEFT JOIN leaf_meta m ON c.leaf = m.leaf
GROUP BY 1,2 ORDER BY 1, n DESC
